### ISSUE TITLE
Make change-language function working

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#1]
![image](https://user-images.githubusercontent.com/56196640/120430443-a8d46500-c394-11eb-9254-244685f75430.png)

If not the entire form you can only change the language of headings in the form.

**Comment by Zhong-Shan-Hui** [comment]
I would like to try to work on this issue. Would you tell me what would be the available languages to select from? It would be English and Hindi right?

**Comment by QAZIMAAZARSHAD** [comment]
Yes, English and Hindi.

Go ahead you can work on this issue.

**Comment by SamikshaSankar** [comment]
I would like to work on this issue under lgn-soc

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue under lgm-soc

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Fine @Zhong-Shan-Hui,

Wait till I review your PR.

**Comment by utkarshgoel10** [comment]
@QAZIMAAZARSHAD I would like to work on this issue, please assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I would like to work on this issue, please assign this to me.
> Also, if assigned can I add a new file (like a new .js) or add my code in existing files.

This issue has already been resolved and will be closed soon.
Look for any other issues.

**Comment by SamikshaSankar** [comment]
@QAZIMAAZARSHAD  this issue is solved?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD this issue is solved?

Yes
