### ISSUE TITLE
Autofill state and district after entering pin code

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#10]
![image](https://user-images.githubusercontent.com/56196640/120439102-c3600b80-c39f-11eb-92ae-a30b71acfa0f.png)

**Comment by Zhong-Shan-Hui** [comment]
Yes I can work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Sure, go-ahead

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by SLPoojitha** [comment]
Could u please assign me this issue sir even I wanted to work on it.

**Comment by QAZIMAAZARSHAD** [comment]
@SLPoojitha I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Since many contributors are willing to resolve this issue, I will accept only the first PR which will completely resolve this issue.

**Comment by SLPoojitha** [comment]
Thank u sir!!

**Comment by QAZIMAAZARSHAD** [comment]
Fine @Zhong-Shan-Hui.

Wait till I review your PR.
