### ISSUE TITLE
Bug fixing in video on/off button on home page

### ISSUE THREAD

**Issue by itsij** [QAZIMAAZARSHAD/Voters-Registration-Portal#109]
ON OFF text on the toggle button on home page is not properly aligned well within button boundaries.

![image](https://user-images.githubusercontent.com/72145053/121777346-33943b80-cbaf-11eb-951b-11ecedc12d5b.png)

![image](https://user-images.githubusercontent.com/72145053/121777296-ee700980-cbae-11eb-8995-a0dd1a78014f.png)

I would like to fix this issue.
@QAZIMAAZARSHAD plz assign this to me under LGM-SOC.

**Comment by QAZIMAAZARSHAD** [comment]
Sure
