### ISSUE TITLE
Make website responsive in mobile phone

### ISSUE THREAD

**Issue by shivshankar9** [QAZIMAAZARSHAD/Voters-Registration-Portal#11]
Site not responsive in phone, needs some changes maybe

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by SLPoojitha** [comment]
Sir, I am a participant of LGMSOC-2021.
Could you please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
@SLPoojitha I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Since many contributors are willing to resolve this issue, I will accept only the first PR which will completely resolve this issue.

**Comment by nitishapiplani** [comment]
I would like to work on it plzz assingn to me lgm SoC participant

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on it plz assign to me LGM SoC participant

@nitishapiplani  I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Since many contributors are willing to resolve this issue, I will accept only the first PR which will completely resolve this issue.

**Comment by V-Yeshwanth** [comment]
I would like to work on this issue !!

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue !!

Go ahead.
But remember, since many contributors are willing to resolve this issue, I will accept only the first PR which will completely resolve this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> Sir @QAZIMAAZARSHAD I would also like to work on it please assign me this task if possible!

@Kartikey0205 I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Since many contributors are willing to resolve this issue, I will accept only the first PR which will completely resolve this issue.
