### ISSUE TITLE
Spelling Mistakes

### ISSUE THREAD

**Issue by mgjain9871** [QAZIMAAZARSHAD/Voters-Registration-Portal#110]
There are 3 drop-down list of states and all there have spelling mistake in the state - "GUJARAT".
It's written "GUJRAT" while it should be "GUJARAT".

![Screenshot (111)_LI](https://user-images.githubusercontent.com/71882225/121777197-7570b200-cbae-11eb-9d37-f20bca1091d8.jpg)

Please assign this issue to me under LGM-SOC.
@QAZIMAAZARSHAD

**Comment by mgjain9871** [comment]
Someone has updated the list of states. So, this issue has been automatically resolved. Hence, u may close this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> Someone has updated the list of states. So, this issue has been automatically resolved. Hence, u may close this issue.

Thanks for notifying.
