### ISSUE TITLE
Date of Birth format wrongly mentioned

### ISSUE THREAD

**Issue by mgjain9871** [QAZIMAAZARSHAD/Voters-Registration-Portal#111]
Date of Birth format should be Day/ Month/ Year  as Date of Birth in the input field is given in this format only.

![Screenshot (113)_LI](https://user-images.githubusercontent.com/71882225/121777521-36dbf700-cbb0-11eb-92ae-df98a66f1341.jpg)

Please assign this issue to me under LGM-SOC.
@QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead

**Comment by QAZIMAAZARSHAD** [comment]
Do changes in both english and hindi page.
