### ISSUE TITLE
No spacing between input fields

### ISSUE THREAD

**Issue by itsij** [QAZIMAAZARSHAD/Voters-Registration-Portal#116]
The city/village input field is a bit overlapping with the select button below it. There is no space in between them.

![image](https://user-images.githubusercontent.com/72145053/121780018-04d09200-cbbc-11eb-925f-92904440c5e1.png)

I would like to fix this issue. 
@QAZIMAAZARSHAD plz assign this to me under LGM-SOC.

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead.

Do changes in both english and hindi page.
