### ISSUE TITLE
Use good quality screenshot in README

### ISSUE THREAD

**Issue by chaitanyasjoshi** [QAZIMAAZARSHAD/Voters-Registration-Portal#12]
The screenshot in the README.md under the sneak peek section is not clear.
High-resolution screenshot can be added so that it is visible to everyone.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by chaitanyasjoshi** [comment]
Sure

**Comment by starrohan999** [comment]
@QAZIMAAZARSHAD 
I would to work on this issue also.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD
> I would to work on this issue also.

@starrohan999 since this is a very easy issue and has already been assigned to someone else, I can't assign it to you.
You can look for any other issues.

**Comment by chaitanyasjoshi** [comment]
@QAZIMAAZARSHAD Is it ok if put the screenshot in the images folder? Or should I create a new folder?
