### ISSUE TITLE
The buttons on/off on the landing page and format of date

### ISSUE THREAD

**Issue by hrshb05** [QAZIMAAZARSHAD/Voters-Registration-Portal#121]
## Describe the bug
1.The on/off button on the home page is not placed correctly
2. The date format is not correct.

@QAZIMAAZARSHAD Please assign this to me under LGM-SOC

**Comment by QAZIMAAZARSHAD** [comment]
Both issues are already open #109, #111.

Before opening any issue make sure that no other similar issue is open.
