### ISSUE TITLE
Stucture the files

### ISSUE THREAD

**Issue by pranavvdesai** [QAZIMAAZARSHAD/Voters-Registration-Portal#122]
structure the folders and file system

**Comment by QAZIMAAZARSHAD** [comment]
Yes, go ahead.

But you have to change the locations of the images and file in code as well.
Also, link every page with every other page.

**Comment by QAZIMAAZARSHAD** [comment]
Before making PR for this check everything very carefully and also share the live demo link with PR.

**Comment by QAZIMAAZARSHAD** [comment]
I have labeled it as level 3, will decrease the label if your work will not be up to the mark.

**Comment by pranavvdesai** [comment]
which image is to be kept?
![image](https://user-images.githubusercontent.com/74852751/121799985-f4b4c300-cc4c-11eb-9678-7c012a138a51.png)

**Comment by QAZIMAAZARSHAD** [comment]
See the current code.

**Comment by QAZIMAAZARSHAD** [comment]
Don't do this way.

Update your repo, fetch upstream, create a separate branch do changes in that then make PR.
