### ISSUE TITLE
Changing the logo of the website

### ISSUE THREAD

**Issue by nisha331** [QAZIMAAZARSHAD/Voters-Registration-Portal#126]
## Is your feature request related to a problem? Please describe.
The logo does not give the prominent feel of the website

## Describe the solution you'd like
I have created 2 logos for the website  one could be put in navbar and 2nd one could be kept as a logo. 

## Additional context
logo
![Untitled design](https://user-images.githubusercontent.com/76838660/121786300-9cde7380-cbdc-11eb-9d20-731fb895c179.png)
for navbar :-1: 
![Sound Perception](https://user-images.githubusercontent.com/76838660/121786310-aa93f900-cbdc-11eb-96a0-51772ae549e7.png)

**Comment by nisha331** [comment]
I as a participant would like to work on this. Kindly /assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
No navbar is fine no need for that.

But it can be used in the title bar.

**Comment by QAZIMAAZARSHAD** [comment]
Upload this pic in the Images folder.

Don't change anything in the code.

**Comment by QAZIMAAZARSHAD** [comment]
#9 this issue is already open and assigned to others, so can't assign to you.

Just upload image in Images folder.

**Comment by nisha331** [comment]
done @QAZIMAAZARSHAD . kindly check it . I had a question, will this be considered as a contribution?

**Comment by QAZIMAAZARSHAD** [comment]
> done @QAZIMAAZARSHAD . kindly check it . I had a question, will this be considered as a contribution?

Yess
