### ISSUE TITLE
Add a scroll to top button 

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Voters-Registration-Portal#13]
There should be scroll to top button
@QAZIMAAZARSHAD can i work on this issue under LGM=SOC'21 participant

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by VaishnaviNigam25** [comment]
PLz, assign me this issue.I wanna add the top button! @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by kumarishalini6** [comment]
@QAZIMAAZARSHAD  I guess the issue is assigned on the basis of first come first serve

**Comment by QAZIMAAZARSHAD** [comment]
@kumarishalini6 since many contributors are willing to resolve the same issue then the best solution will be accepted.

**Comment by V-Yeshwanth** [comment]
I would like to work on this issue !!

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue !!

Go ahead.
But keep in mind since many contributors are working on this issue only the best design will be accepted.

**Comment by QAZIMAAZARSHAD** [comment]
Great job @kumarishalini6. I'll merge your PR tomorrow.

**Comment by kumarishalini6** [comment]
Ok
