### ISSUE TITLE
Margin at the bottom of the form

### ISSUE THREAD

**Issue by Anupam-Panwar** [QAZIMAAZARSHAD/Voters-Registration-Portal#14]
* Bottom Margin of the form is bit less as compared to other three sides

![image](https://user-images.githubusercontent.com/65714751/120746014-f62f0e80-c51b-11eb-86a8-f57ef4bf0123.png)

* I would like to work on this

**Comment by QAZIMAAZARSHAD** [comment]
@Anupam-Panwar there is another issue (Design a new creative footer) https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/4.
I think this margin issue will be handled there, so no need to create a new issue.

If you have any better ideas for the footer you can work on issue number https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/4

**Comment by Anupam-Panwar** [comment]
@QAZIMAAZARSHAD I thought that issue will deal with design of new footer only.
