### ISSUE TITLE
Fixing a typo & Improving footer section

### ISSUE THREAD

**Issue by ArshWalker** [QAZIMAAZARSHAD/Voters-Registration-Portal#140]
## Describe the bug
![image](https://user-images.githubusercontent.com/54627391/121800495-f2079d00-cc4f-11eb-83c0-30d389825adc.png)

## Improving Footer:
- changing font-family
- Adding Social media icons.

**Comment by ArshWalker** [comment]
@QAZIMAAZARSHAD Please assign me under LGMSOC21

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead

**Comment by nlok5923** [comment]
@ArshWalker please can you update us about this issue how's it's going or you need any help

**Comment by QAZIMAAZARSHAD** [comment]
This issue was open 7 days ago, a lot of updates have occurred since then.

This issue no longer exists.

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD can you please check my dm at discord.
