### ISSUE TITLE
Removing video on/off switch 

### ISSUE THREAD

**Issue by pallavi-1812** [QAZIMAAZARSHAD/Voters-Registration-Portal#144]
## Is your feature request related to a problem? Please describe.
Currently, the video switch toggle button is just in front of the video and it is impairing the look of the website. Thus I would like to move the toggle button to footer so that it does not interfere with the front look of the video. 

## Describe the solution you'd like
I would like to move the toggle button to footer .
![Annotation 2021-06-13 144303](https://user-images.githubusercontent.com/67572675/121801591-b374e100-cc55-11eb-9a55-5eaa6dd29d37.png)

## Additional context
Add any other context about the feature request here.

**Comment by dilshadRaza** [comment]
I would like to move the toggle

**Comment by QAZIMAAZARSHAD** [comment]
It's better to remove it.

No need for this button.

**Comment by QAZIMAAZARSHAD** [comment]
@pallavi-1812 delete this button.

**Comment by QAZIMAAZARSHAD** [comment]
> It's better to remove it.
> 
> No need for this button.

Already assigned, look for some other issue.

**Comment by QAZIMAAZARSHAD** [comment]
@dilshadRaza you can work on this issue now.

Remove video On/Off switch from index.html.

**Comment by QAZIMAAZARSHAD** [comment]
Only the first PR will be accepted since more than one participant is working on this.

**Comment by dilshadRaza** [comment]
> @dilshadRaza you can work on this issue now.
> 
> Remove video On/Off switch from index.html.

thank you sir 
I will remove this on/off button

**Comment by QAZIMAAZARSHAD** [comment]
> > @dilshadRaza you can work on this issue now.
> > Remove video On/Off switch from index.html.
> 
> thank you sir
> I will remove this on/off button

This issue has been resolved now.

Sorry @dilshadRaza their has been a misunderstanding that's why I assigned you.

**Comment by dilshadRaza** [comment]
> > > @dilshadRaza you can work on this issue now.
> > > Remove video On/Off switch from index.html.
> > 
> > 
> > thank you sir
> > I will remove this on/off button
> 
> This issue has been resolved now.
> 
> Sorry @dilshadRaza their has been a misunderstanding that's why I assigned you.

its ok
no problem sir
