### ISSUE TITLE
Add any other Image or video in background instead of current video.

### ISSUE THREAD

**Issue by GaurPeeyush** [QAZIMAAZARSHAD/Voters-Registration-Portal#145]
When the video plays in the background, it makes the site look unattractive and messed up. Also, the video is referring to foreign culture whereas the site is meant for Indian voters.

So I suggest either you change the current background video and add any other one which also matches with the theme of the website, or instead of any video just add any image related to voting and all,  by doing this, you'll get rid of that toggle button also.

**Comment by GaurPeeyush** [comment]
Kindly assign me, I'd like to work on this issue :)

**Comment by danascape** [comment]
If you want to contribute, just create a pull request with changes.

**Comment by QAZIMAAZARSHAD** [comment]
> If you want to contribute, just create a pull request with changes.

No never do that.
First, open an issue, ask the project admin to assign you then only start working on it.
And always mention issue number with PR.

**Comment by QAZIMAAZARSHAD** [comment]
> When the video plays in the background, it makes the site look unattractive and messed up. Also, the video is referring to foreign culture whereas the site is meant for Indian voters.
> 
> So I suggest either you change the current background video and add any other one which also matches with the theme of the website, or instead of any video just add any image related to voting and all, by doing this, you'll get rid of that toggle button also.

ok go ahead.

**Comment by QAZIMAAZARSHAD** [comment]
Make sure video quality is good and size is small.

**Comment by danascape** [comment]
> > If you want to contribute, just create a pull request with changes.
> 
> No never do that.
> First, open an issue, ask the project admin to assign you then only start working on it.
> And always mention issue number with PR.

I see

**Comment by GaurPeeyush** [comment]
The changes introduced fixes issue #145.
I've added a new video file in the background of the index.html, which makes the website look better than before.
Do review my code once and merge the pull request :)

**Comment by Sakshi1007** [comment]
Assign this to me please.

**Comment by Sakshi1007** [comment]
Working on it.
