### ISSUE TITLE
Surname shouldn't be made mandatory to enter.

### ISSUE THREAD

**Issue by GaurPeeyush** [QAZIMAAZARSHAD/Voters-Registration-Portal#146]
An asterisk is mentioned with Surname where it's written (if any), but asterisk makes it mandatory to enter.

So to make it optional detail to be entered we have to remove the asterisk after it.
![Screenshot (239)](https://user-images.githubusercontent.com/81735768/121803663-4fa3e580-cc60-11eb-85fc-ff10d2473b8f.png)

**Comment by GaurPeeyush** [comment]
I'd like to work on this issue.
Kindly assign :)

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead.

**Comment by GaurPeeyush** [comment]
Issue #146 is fixed with this update of Home.html.
Kindly check the code and merge the pull request :)
After merging I'd prefer that you only close this issue.
