### ISSUE TITLE
Adding Navigation bar to the website

### ISSUE THREAD

**Issue by Aiswarika** [QAZIMAAZARSHAD/Voters-Registration-Portal#15]
I would like to add a navbar to the website. @QAZIMAAZARSHAD Can you please assign me this issue?

**Comment by QAZIMAAZARSHAD** [comment]
@Aiswarika can you elaborate your idea because I don't see what is the use of the navigation bar on this website.

This is just an online demo version of an application form.

**Comment by V-Yeshwanth** [comment]
I would like to work on this issue !!

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue !!

@V-Yeshwanth this issue will be dealt in issue number https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/20.
