### ISSUE TITLE
Display document type in drop down list

### ISSUE THREAD

**Issue by Aiswarika** [QAZIMAAZARSHAD/Voters-Registration-Portal#16]
I would like to work on this issue if needed. @QAZIMAAZARSHAD Can you please assign me this issue?

![Screenshot (382)](https://user-images.githubusercontent.com/72227445/120889016-dc272600-c618-11eb-81ce-fb217837c7ec.png)

**Comment by VaishnaviNigam25** [comment]
I would like to work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Sure,

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by VaishnaviNigam25** [comment]
> Sure,
> 
> I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

Ok @QAZIMAAZARSHAD  👍

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue.

@VaishnaviNigam25 since this is a very easy issue I cannot assign it to more than one participant.
You can look for another issue or open a new one.

I apologize for not mentioning it earlier.

**Comment by Aiswarika** [comment]
@QAZIMAAZARSHAD Kindly review my PR and let me know if it's fine.
