### ISSUE TITLE
Spelling and  grammatical errors in README.md

### ISSUE THREAD

**Issue by GaurPeeyush** [QAZIMAAZARSHAD/Voters-Registration-Portal#161]
## Describe the bug
It should be "sneak peek" instead of "sneek peek" in README.md
## To Reproduce
Update README.md

## Expected behavior
"sneek peek" would be changed to "sneak peek"

**Comment by GaurPeeyush** [comment]
I'd like to work on this issue.
Kindly assign me :)

**Comment by QAZIMAAZARSHAD** [comment]
But this is too small issue.

Look for other grammatical and spelling mistakes as well.

**Comment by GaurPeeyush** [comment]
All the spelling and grammatical mistakes in README.md are rectified.
Do check it out once and merge the pull request :)
Henceforth, close this issue.
