### ISSUE TITLE
Improve UI of Landing page

### ISSUE THREAD

**Issue by dpshikha476** [QAZIMAAZARSHAD/Voters-Registration-Portal#163]
I want to improve the header UI  and the start button design for landing page.
Will you pls assign me this under LGM-SOC'21?

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead.

The site is responsive in mobile as well. Check responsiveness also while making any changes.

**Comment by dpshikha476** [comment]
> Go ahead.
> 
> The site is responsive in mobile as well. Check responsiveness also while making any changes.

Sure!
