### ISSUE TITLE
Start button is not clickable

### ISSUE THREAD

**Issue by itsij** [QAZIMAAZARSHAD/Voters-Registration-Portal#167]
## Describe the bug
The entire start button on home page is not clickable. Only the text written on it "Start" is clickable.

## To Reproduce
1. Go to the home page
2. Click on start button but not on the "start" text written on it
3. next page will not open
4. it will open only after clicking on "start" text 

## Expected behavior
Entire button should be clickable, not just the hyperlink.

## Environment (please complete the following information):
 - OS: Windows
 - Browser: Chrome

@QAZIMAAZARSHAD I would like to fix this bug as LGMSOC Participant. Plz assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
Which button.

The start button is perfectly working?

**Comment by itsij** [comment]
If u click this green marked area on the start button, then it will not take u to next page. Next page (login page) will open only if u click on the hypertext. So, i mean to say that entire button is not clickable, only the hypertext is clickable.

![image](https://user-images.githubusercontent.com/72145053/121924863-f02a0080-cd59-11eb-87e4-8ad6c90d0e2a.png)

**Comment by itsij** [comment]
If u click this green marked area on the start button, then it will not take u to next page. Next page will open only if u click on the hypertext on the button. So, i mean to say that the entire button is not clickable, only the hypertext "Start" written on it is clickable.
 @QAZIMAAZARSHAD 
![image](https://user-images.githubusercontent.com/72145053/121926086-36339400-cd5b-11eb-8c5b-1269c326e2fa.png)
