### ISSUE TITLE
Flag takes a lot of time to glow on hover

### ISSUE THREAD

**Issue by Sukhseerat-Kaur** [QAZIMAAZARSHAD/Voters-Registration-Portal#168]
## Describe the bug
Flag on the upper left corner takes a lot of time to glow on hover. It should be fixed.

## Expected behavior
The glow up of the flag should be immediate as soon as a hover is there.

## Environment (please complete the following information):
 - OS: Windows 
 - Browser: Chrome

**Comment by Sukhseerat-Kaur** [comment]
@QAZIMAAZARSHAD Please let me change this. Assign me this under LGMSOC'21

**Comment by Salonee-Jain** [comment]
Can I work on this issue under LGMSOC'21

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this issue under LGMSOC'21

Look for some other issue, this is already assigned.

**Comment by SS-Ace** [comment]
Goodevening sir, i have fixed this issue. Can i upload it or should i work on some other issue? If i can upload then can you guide me?

**Comment by QAZIMAAZARSHAD** [comment]
> Goodevening sir, i have fixed this issue. Can i upload it or should i work on some other issue? If i can upload then can you guide me?

If you have solved the issue, make pull request.

First, update your repo, fetch upstream then make changes then make PR.

**Comment by Sukhseerat-Kaur** [comment]
@QAZIMAAZARSHAD But this issue was assigned to me.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD But this issue was assigned to me.

Yes, and it is still assigned to you, I have not merged any PR for this issue.

**Comment by Sukhseerat-Kaur** [comment]
@QAZIMAAZARSHAD I opened a PR #177 solving this issue
