### ISSUE TITLE
Favicon in every page

### ISSUE THREAD

**Issue by Jagannath8** [QAZIMAAZARSHAD/Voters-Registration-Portal#178]
## Describe the solution you'd like
Adding favicon in every page

**Comment by Jagannath8** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by QAZIMAAZARSHAD** [comment]
Use this logo -> https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/blob/master/Images/flag.png.

**Comment by tanzzz-tech** [comment]
can u plz assigm me this issue?i can add the logo in title section

**Comment by QAZIMAAZARSHAD** [comment]
> can u plz assign me this issue?i can add the logo in title section

@Jagannath8 if you didn't solve this issue till tomorrow then I will assign @tanzzz-tech.

**Comment by Amrutha1101** [comment]
Can you assign me this issue?

**Comment by QAZIMAAZARSHAD** [comment]
> Can you assign me this issue?

Many people are ahead in line.
Look for some other issue.

**Comment by Jagannath8** [comment]
This issue is already solved by someone.

**Comment by QAZIMAAZARSHAD** [comment]
> This issue is already solved by someone.

https://qazimaazarshad.github.io/Voters-Registration-Portal/

Check again, not a single page has a favicon.

**Comment by QAZIMAAZARSHAD** [comment]
Use this logo -> https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/blob/master/Images/flag.png
