### ISSUE TITLE
Add favicon to the website 

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Voters-Registration-Portal#18]
I would like to work on this issue under LGM-SOC , Can you please assign me @QAZIMAAZARSHAD

**Comment by VaishnaviNigam25** [comment]
Hey I would like to work on this..Please assign me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open, see issue number https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/9.

Look for any other issues or open new issues.
