### ISSUE TITLE
Email validation is not Done properly and it must be Done on backend also because  HTML,js can be edited too

### ISSUE THREAD

**Issue by engineerscodes** [QAZIMAAZARSHAD/Voters-Registration-Portal#180]
<img   width="500px" height="900px"   src="https://user-images.githubusercontent.com/68312849/122097661-8a0ead80-ce2d-11eb-95e5-9f03c4772610.png" >

![image](https://user-images.githubusercontent.com/68312849/122097710-9a268d00-ce2d-11eb-9a2e-4be8cd2b19c6.png)

**Comment by nlok5923** [comment]
@engineerscodes how's going can you please share some updates ?

**Comment by RituCs** [comment]
I would like to work on this issue under LGMSOC'21 if no one is working. Please assign this issue to me.

**Comment by engineerscodes** [comment]
Created pr plz check #288

**Comment by engineerscodes** [comment]
> @engineerscodes how's going can you please share some updates ?

I had my exam's
