### ISSUE TITLE
Add logo in title section

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Voters-Registration-Portal#187]
## Is your feature request related to a problem? Please describe.
Logo feature is not added in login.html and signup.html

## Describe the solution you'd like
Indian flag must be added in title section of login and signup page

## Additional context
![login title](https://user-images.githubusercontent.com/56637948/122121877-bf28f900-ce49-11eb-84a6-106ce6cd17b8.jpg)
![signup_title](https://user-images.githubusercontent.com/56637948/122121908-c7813400-ce49-11eb-8afa-b6a25cf978c4.jpg)

**Comment by gargi111** [comment]
I would like to fix this issue as LGM   SOC21.participant .pls assign this work to me .

**Comment by QAZIMAAZARSHAD** [comment]
@royalleads15, @gargi111, and @sameer2403 this issue is already open #178.

Before opening any issue make sure that no other similar issue is open.
