### ISSUE TITLE
ON OFF button at indexpage

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Voters-Registration-Portal#190]
## Describe the bug
When i put video at index.html page and create a on off button that time it was working but now it's not working. Maybe mistaken by some participant.
@QAZIMAAZARSHAD I want to resolve this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> ## Describe the bug
> When i put video at index.html page and create a on off button that time it was working but now it's not working. Maybe mistaken by some participant.
> @QAZIMAAZARSHAD I want to resolve this issue.

Yes, due to an update.

But I think their is no need for that button, an issue to remove it already open #144.
