### ISSUE TITLE
Adding scroll bottom to top button

### ISSUE THREAD

**Issue by mdinesh124** [QAZIMAAZARSHAD/Voters-Registration-Portal#194]
## Describe the solution you'd like
Adding  a bottom to top button ensures scrolling the page from bottom to top in just one button click.

**Comment by mdinesh124** [comment]
@QAZIMAAZARSHAD I would work on this issue under LGMSOC.

**Comment by QAZIMAAZARSHAD** [comment]
@mdinesh124 have a look at the website -> https://qazimaazarshad.github.io/Voters-Registration-Portal/.

Before doing any activity always verify.
