### ISSUE TITLE
Create a logout button on registration portal

### ISSUE THREAD

**Issue by pruthvirajjadhav1** [QAZIMAAZARSHAD/Voters-Registration-Portal#197]
On clicking the logout button user should be redirected to the login page,

Create logout button on home.html and formcorrection.html.

**Comment by QAZIMAAZARSHAD** [comment]
Create a logout button on home.html, whenever users click on log out a pop-up should appear "Are you sure you want to log out your changes have not been saved" then it takes the user back to the login page.

Also, try to add something like logged in Mr. XYZ. If you can. Else just create a logout button.

**Comment by tanzzz-tech** [comment]
can u assign me this issue i have better ideas like i can create a prompt as well "do u want to logout"?

**Comment by QAZIMAAZARSHAD** [comment]
> can u assign me this issue i have better ideas like i can create a prompt as well "do u want to logout"?

Already assigned to others.

**Comment by pruthvirajjadhav1** [comment]
Can anyone help me  I had creates a logout button but I cant redirect it to the login portal after clicking it can anyone help me.

**Comment by QAZIMAAZARSHAD** [comment]
> Can anyone help me I had creates a logout button but I cant redirect it to the login portal after clicking it can anyone help me.

See other buttons like the help button how it is redirecting to other pages.

**Comment by jatinjain001** [comment]
I would like to work on it please let me know if it is available

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on it please let me know if it is available

Others are already working on this issue.
Look for other issues.

**Comment by QAZIMAAZARSHAD** [comment]
@jatinjain001, @tanzzz-tech, and @sameer2403 any updates?

**Comment by dilroseR** [comment]
Can i try this?

**Comment by QAZIMAAZARSHAD** [comment]
> Can i try this?

DCP or LGMSoC?

**Comment by dilroseR** [comment]
> > Can i try this?
> 
> DCP or LGMSoC?

dcp

**Comment by dilroseR** [comment]
> Create a logout button on home.html, whenever users click on log out a pop-up should appear "Are you sure you want to log out your changes have not been saved" then it takes the user back to the login page.
> 
> Also, try to add something like logged in Mr. XYZ. If you can. Else just create a logout button.

i need to do only these changes right?

**Comment by QAZIMAAZARSHAD** [comment]
On clicking the logout button user should be redirected to the login page,

Create logout button on home.html and formcorrection.html.
