### ISSUE TITLE
While signup if input gets wrong it reset the whole form.

### ISSUE THREAD

**Issue by pruthvirajjadhav1** [QAZIMAAZARSHAD/Voters-Registration-Portal#198]
## Describe the bug
While filling the signup form if something wrong has been input then the whole form gets reset

## Expected behavior
While filling the form if something wrong gets input it should show an error but it should not reset the whole form.

## Environment (please complete the following information):
 - OS: Windows 10
 - Browser: Crome

**Comment by QAZIMAAZARSHAD** [comment]
Already resolved.
