### ISSUE TITLE
Some of the text on registration page is out side the box

### ISSUE THREAD

**Issue by pruthvirajjadhav1** [QAZIMAAZARSHAD/Voters-Registration-Portal#199]
## Describe the bug
On the registration form, some information is crossed the information box.

![Screenshot (5)](https://user-images.githubusercontent.com/73253354/122226102-42426180-ced3-11eb-9fa3-dd727884721a.png)

**Comment by QAZIMAAZARSHAD** [comment]
No everything's fine, 
![Screenshot (126)](https://user-images.githubusercontent.com/56196640/122226877-ff34be00-ced3-11eb-8eec-c5e30a72d797.png)

Maybe you have zoomed or minimized the screen.
