### ISSUE TITLE
Make zoom in/zoom out buttons functional

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#2]
![image](https://user-images.githubusercontent.com/56196640/120430550-d02b3200-c394-11eb-9087-331def4ccdd9.png)

**Comment by Shivamyana19** [comment]
hii , I would like to work on this issue. Please assign it to me

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Shivamyana19** [comment]
> I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

ok

**Comment by 1anshu-56** [comment]
I want to work on this issue can you please assign it to me, I want to work on this issue.

**Comment by 1anshu-56** [comment]
Thanks for assigning @QAZIMAAZARSHAD

**Comment by Kartikey0205** [comment]
@QAZIMAAZARSHAD Please assign me this too!!

**Comment by nandinimalik16** [comment]
Please assign me this issue

**Comment by utkarshgoel10** [comment]
@QAZIMAAZARSHAD I have prior knowledge on how to accomplish this task, so please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
Remember first and better PR will be accepted.

**Comment by nitishapiplani** [comment]
i would like to work on this issue if possible lgmsoc21 participant

**Comment by QAZIMAAZARSHAD** [comment]
> i would like to work on this issue if possible lgmsoc21 participant

Already assigned to many.
Look for any other issue.
