### ISSUE TITLE
Design a Home page

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Voters-Registration-Portal#20]
@QAZIMAAZARSHAD  i think there should be a styled, attractive home page  , there should be a button after clicking on that button voters can enter on the main that.

@QAZIMAAZARSHAD can i work on this issue under LGM-SOC'21

**Comment by QAZIMAAZARSHAD** [comment]
Ok, go ahead

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by kumarishalini6** [comment]
Ok

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by QAZIMAAZARSHAD** [comment]
> Hii, I would like to work on this issue as an LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by QAZIMAAZARSHAD** [comment]
> Hii, I would like to work on this issue as an LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.
Since many contributors are willing to resolve this issue, keep in mind the best design/solution will be accepted.

**Comment by QAZIMAAZARSHAD** [comment]
Great job @kumarishalini6, I'll merge your PR tomorrow.

**Comment by kumarishalini6** [comment]
Ok thanks

**Comment by aditya687** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. I can beautifully design the home page with header section, about us, home page and give a elegant design to the page

**Comment by QAZIMAAZARSHAD** [comment]
> Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. I can beautifully design the home page with header section, about us, home page and give a elegant design to the page

@aditya687 this issue has been resolved and will be closed soon.
If you have any better ideas you are always welcome to open new issues. Wait till I merge above PR.
