### ISSUE TITLE
Add LGM-SOC'21 score card in readme.md

### ISSUE THREAD

**Issue by ishitakapoor26** [QAZIMAAZARSHAD/Voters-Registration-Portal#201]
Add LGM-SOC'21 score card in readme.md

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD pls assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
How do you plan to do that?

**Comment by ishitakapoor26** [comment]
> How do you plan to do that?

Here is a screenshot
![Uploading score card.PNG…]()

**Comment by ishitakapoor26** [comment]
> How do you plan to do that?

@QAZIMAAZARSHAD Here is the ss
![score card](https://user-images.githubusercontent.com/78542333/122349015-6d779000-cf69-11eb-9ec1-1b6f745f0ceb.PNG)

**Comment by QAZIMAAZARSHAD** [comment]
Oo you mean this, I thought you were saying points of all the contestants.

**Comment by QAZIMAAZARSHAD** [comment]
Ok add it in the open source program section, and don't add a large screenshot.

**Comment by ishitakapoor26** [comment]
@QAZIMAAZARSHAD can I add this to your other projects also?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD can I add this to your other projects also?

Okk open the issues, and ask me to assign you.

Also, you have added it below the letsgrowmore logo, Add it just beside the logo in the same section.
