### ISSUE TITLE
Modifying the login portal

### ISSUE THREAD

**Issue by Swarga-codes** [QAZIMAAZARSHAD/Voters-Registration-Portal#203]
It was an amazing website to be honest and I think that the login portal could be made much better , so @QAZIMAAZARSHAD  can you please /assign me with the task of improving upon the CSS of the login page.

**Comment by tanzzz-tech** [comment]
can u please assign me this issue i am a lgm soc participant can make a better one?which ever page u like merge it but if possible assign me too!

**Comment by QAZIMAAZARSHAD** [comment]
> can u please assign me this issue i am a lgm soc participant can make a better one?which ever page u like merge it but if possible assign me too!

okk go ahead.

But remember the first and better solution will be accepted.

**Comment by harshita9621** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this issue? I'm a participant of LGM Soc21.

This issue has already been resolved, PR not merged due to conflicts.
