### ISSUE TITLE
Selecting Language Option to change language isn't visible

### ISSUE THREAD

**Issue by Sourav61** [QAZIMAAZARSHAD/Voters-Registration-Portal#207]
When we come to the Home page of the website, i am not able to see any option to change the language.
![Capture7](https://user-images.githubusercontent.com/70853906/122512254-387d4300-d026-11eb-87e4-d332074d6468.JPG)

@QAZIMAAZARSHAD Sir, Can you pls assign me this issue??

**Comment by QAZIMAAZARSHAD** [comment]
![Screenshot (132)](https://user-images.githubusercontent.com/56196640/122513449-0f5db200-d028-11eb-8214-df924134a87f.png)
 It is fine, maybe some issue with your window screen( zoom/zzom out).
