### ISSUE TITLE
Footer content

### ISSUE THREAD

**Issue by RiyaGupta89** [QAZIMAAZARSHAD/Voters-Registration-Portal#209]
![6](https://user-images.githubusercontent.com/72425181/122544519-8441e380-d04a-11eb-847f-363a34cd9b47.png)
The footer content has no padding on the top. Please assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 you can work on issue number https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/4.

Ping me there to assign you.
