### ISSUE TITLE
Create a similar form for correction of voter details

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Voters-Registration-Portal#21]
I would like to work on this issue please assign me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD Sir I would also like to work on it , do assign me if possible

**Comment by coding-geek21** [comment]
@QAZIMAAZARSHAD Due to Exams I was not able to work on this issue, I have made a PR please do check it. Thank you

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Due to Exams I was not able to work on this issue, I have made a PR please do check it. Thank you

Will review soon.
