### ISSUE TITLE
Improve footer design

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#216]
Design footer like this 
![image](https://user-images.githubusercontent.com/56196640/122638752-8ae85d80-d113-11eb-9acd-a824126d484d.png)

**Comment by RiyaGupta89** [comment]
I can work on this issue. Can you tell me the content which should be included in the footer?

**Comment by QAZIMAAZARSHAD** [comment]
Make it exact same.

Just replace words like UIDAI with national voter portal.
copyright voter portal rights reserved by Qazi Maaz etc.

**Comment by RiyaGupta89** [comment]
![1](https://user-images.githubusercontent.com/72425181/122642161-9db85d80-d126-11eb-9fde-d8664b191f0b.png)
Please have a look if this looks okay?

**Comment by RiyaGupta89** [comment]
Should I request for PR?

**Comment by RiyaGupta89** [comment]
You want this footer on all the pages, right? Like on signup page, login page, home page, and the opening page, right?

**Comment by QAZIMAAZARSHAD** [comment]
> ![1](https://user-images.githubusercontent.com/72425181/122642161-9db85d80-d126-11eb-9fde-d8664b191f0b.png)
> Please have a look if this looks okay?

The bottom of the footer doesn't look nice.
Remove tabs of home, help, login, etc.
Move the help desk button in the contact us section above follow us. And redesign the button like other things in the footer.
And the position of copyright text is fine but the background should be transparent like the rest of the footer.


And add the footer on every page except index.html.

**Comment by harshita9621** [comment]
Can I work on this issue? I'm a participant of LGM Soc21.

**Comment by RiyaGupta89** [comment]
@harshita9621 Bro, I am working on this issue. There are many other issues, find one that is suitable to you.

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this issue? I'm a participant of LGM Soc21.

Yess, Already assigned.

Look for some other issues.

**Comment by RiyaGupta89** [comment]
![9](https://user-images.githubusercontent.com/72425181/122669054-18da4c00-d1d9-11eb-9f32-78f2411d9a7d.png)
Does this look okay?

**Comment by QAZIMAAZARSHAD** [comment]
Cool, 

Add a little bit of padding between the footer and end of the form.

**Comment by QAZIMAAZARSHAD** [comment]
Try to make the help button transparent.

**Comment by RiyaGupta89** [comment]
Added the padding between footer and end of the form.
And the help button looks like this if I'm making it transparent, won't look that good. On hover it does the background color white and color black.
![a](https://user-images.githubusercontent.com/72425181/122669539-838c8700-d1db-11eb-8de5-97c800aa8c33.PNG)

**Comment by RiyaGupta89** [comment]
Should I commit my code? @QAZIMAAZARSHAD

**Comment by RiyaGupta89** [comment]
Or you want some more changes? @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> Added the padding between footer and end of the form.
> And the help button looks like this if I'm making it transparent, won't look that good. On hover it does the background color white and color black.
> ![a](https://user-images.githubusercontent.com/72425181/122669539-838c8700-d1db-11eb-8de5-97c800aa8c33.PNG)

Okk fine, do whatever you feel that looks good.

Then make PR. Add footer in all pages except index.html.

**Comment by RiyaGupta89** [comment]
Done.

**Comment by harshita9621** [comment]
@QAZIMAAZARSHAD Can I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Can I work on this issue?

Already assigned.
