### ISSUE TITLE
Make a similar form in Hindi Language 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [QAZIMAAZARSHAD/Voters-Registration-Portal#22]
![16229632055911981222179083962529](https://user-images.githubusercontent.com/75005433/120915878-e2261100-c6c3-11eb-8a20-e5893983ebcf.jpg)

I am a Lgm-Soc'21 participant 
When we click on the hindi option the page still remains in English language so my idea is to create a similar page in hindi language as hindiindex.html and link that html file to the hindi option using anchor tag so when a user clicks on hindi the same page will appear in hindi language although it would be a tedious task but I would like to take up this challenge 

Please assign this issue to me @QAZIMAAZARSHAD sir I an a LGM-SOC'21 Participant

**Comment by QAZIMAAZARSHAD** [comment]
@Vedant-Jayesh-Oza this issue is already open see issue number https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/1
