### ISSUE TITLE
Properly align emblem image

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Voters-Registration-Portal#223]
## Describe the bug
float satyamev jayate image to left so that it cannot override header and a bug in dark night mode toogle switch button

![bug](https://user-images.githubusercontent.com/56637948/122708881-cea9a700-d27a-11eb-998a-7fd04e6b0a19.jpg)

**Comment by QAZIMAAZARSHAD** [comment]
There is no such bug when I open website.

![image](https://user-images.githubusercontent.com/56196640/122709935-e41fd080-d27c-11eb-96e7-d41e95d96d69.png)

**Comment by QAZIMAAZARSHAD** [comment]
But shift emblem image a little towards left.

Check responsiveness as well.


Do changes in every page.

**Comment by asdsyd** [comment]
Can I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this issue?

This issue is already assigned look for some other issues.

**Comment by QAZIMAAZARSHAD** [comment]
@royalleads15 I suggest finishing basic and simple issues first.

**Comment by royalleads15** [comment]
Sure sir
