### ISSUE TITLE
Adjust print button in mobile view

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#225]
![image](https://user-images.githubusercontent.com/56196640/122746275-7b9a1900-d2a7-11eb-993a-c534bdfd8938.png)

**Comment by royalleads15** [comment]
I am ready to work on that, please do assign me

**Comment by royalleads15** [comment]
![prnt1](https://user-images.githubusercontent.com/56637948/122758984-16e6ba80-d2b7-11eb-85de-f70a5b8ac8b3.jpg)
![prnt2](https://user-images.githubusercontent.com/56637948/122758996-19e1ab00-d2b7-11eb-812a-9c459da1f1ae.jpg)
Sir have a look on this, if this is right I can make PR.

**Comment by QAZIMAAZARSHAD** [comment]
Remove it from the header, add it below select language or in the same line of "Note field marked with asterisks".

Do it for both mobile and desktop views.

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD Sir this issue is also resolved in #231
