### ISSUE TITLE
Improve print form functionality

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#226]
Print function prints the entire web page including header, footer, captcha, etc.

It should work properly and only the submitted form should be printed.

**Comment by royalleads15** [comment]
Sir I think I can improve it more, assign me so that I can continue.

**Comment by RiyaGupta89** [comment]
Where is the print function? I can't find it.

**Comment by QAZIMAAZARSHAD** [comment]
> Where is the print function? I can't find it.

In the header of home.html.

**Comment by RiyaGupta89** [comment]
> > Where is the print function? I can't find it.
> 
> In the header of home.html.

Sorry, I still cannot see it. Is the print button not there in the home page on the website? You can tell me the location of it and I'll find it.

**Comment by RiyaGupta89** [comment]
Oh, I saw it. Okay. No need to answer now.

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD I removed footer part. Tell me about the header, from where you want it to print? from mandatory specifications? Or from somewhere else?

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD From form 6?

**Comment by QAZIMAAZARSHAD** [comment]
Yes from form 6 to I am aware signature.

**Comment by RiyaGupta89** [comment]
![print2](https://user-images.githubusercontent.com/72425181/122797156-cc783480-d2dc-11eb-81af-38c264283509.png)
![print1](https://user-images.githubusercontent.com/72425181/122797160-ceda8e80-d2dc-11eb-9335-fbc38243408e.png)
Have a look, is it okay? Or you want something more to exclude from the print page?

**Comment by QAZIMAAZARSHAD** [comment]
> ![print2](https://user-images.githubusercontent.com/72425181/122797156-cc783480-d2dc-11eb-81af-38c264283509.png)
> ![print1](https://user-images.githubusercontent.com/72425181/122797160-ceda8e80-d2dc-11eb-9335-fbc38243408e.png)
> Have a look, is it okay? Or you want something more to exclude from the print page?

@RiyaGupta89 the printed form should include filled details.

This was the mistake in @royalleads15 latest PR and also print form function is printing everything including the footer in mobile view.

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD  My PR resolves all of these issues. Please review it.

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD Is there something more to change?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Is there something more to change?

I mentioned everything in PR.

**Comment by RiyaGupta89** [comment]
> > @QAZIMAAZARSHAD Is there something more to change?
> 
> Submitted details in the form are not getting printed.

If the user is printing the form before submitting it then the details are getting printed. After that its not getting printed before the form refreshes.

**Comment by QAZIMAAZARSHAD** [comment]
> > > @QAZIMAAZARSHAD Is there something more to change?
> > 
> > 
> > Submitted details in the form are not getting printed.
> 
> If the user is printing the form before submitting it then the details are getting printed. After that its not getting printed before the form refreshes.

No even without submitting it is not printing the entered details.

Share screenshots if so.

**Comment by QAZIMAAZARSHAD** [comment]
@royalleads15 and @RiyaGupta89 you can work on issue #246 to fix the bugs.
