### ISSUE TITLE
Website lacks responsiveness over some resolutions 

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#227]
## Describe the bug
An extra spacing has been encountered while taking website tour at lower resolutions

## To Reproduce
1.  Header over to voter login page
2.  resize page
3. See issue
4. 

## Expected behavior
The should not be any extra spacing

## Logs
![image](https://user-images.githubusercontent.com/56120084/122771138-c75abb80-d2c3-11eb-913e-eb7ca9a07c13.png)

## Environment (please complete the following information):
 - OS: all
 - Browser: all

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD can you please confirm it ?

**Comment by RiyaGupta89** [comment]
Can I work on it after finishing my other two issues?

**Comment by nlok5923** [comment]
Sure

**Comment by RiyaGupta89** [comment]
Can you specify what are the those resolations on which website lacks responsivess? Or there are just two of them?

**Comment by nlok5923** [comment]
you can tru around 158 x 677

**Comment by Albert-Jokelin** [comment]
Hey! Can I try fixing this?

**Comment by nlok5923** [comment]
Sure go ahead assigning you.

**Comment by harishpansari** [comment]
assign to me @nlok5923 I can do this.

**Comment by QAZIMAAZARSHAD** [comment]
> assign to me @nlok5923 I can do this.

Someone is already working on this.

**Comment by harishpansari** [comment]
> > assign to me @nlok5923 I can do this.
> 
> Someone is already working on this.

ok

**Comment by Albert-Jokelin** [comment]
Hey!
I've completed the responsiveness of the website upto a width of 425px. I've deployed it on Netlify so that you can check it out. After that I'll create a PR.

https://suspicious-clarke-a869e9.netlify.app

**Comment by RiyaGupta89** [comment]
@Albert-Jokelin Top right icon which is for dark mode and light mode in slightly unresponsive. When you click on light mode, the user can see the moon which is not properly hidden. Check once.

**Comment by Albert-Jokelin** [comment]
@RiyaGupta89 The changes are still being deployed, should be visible in a few minutes

**Comment by RiyaGupta89** [comment]
@Albert-Jokelin Okay.
