### ISSUE TITLE
Include JavaScript in tech stack section of readme

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#228]
## Describe the bug
Current readme only has html and css as tech stack for website 

## To Reproduce
1.  Head over to readme tech stack section

## Expected behavior
Include JS  logo as one of the stack for website

## Logs
add JS image too
![image](https://user-images.githubusercontent.com/56120084/122771662-44863080-d2c4-11eb-8c45-b20f2bb95f3f.png)

## Environment (please complete the following information):
 - OS: all
 - Browser: all

## Additional context
none

**Comment by naveen8801** [comment]
Hi @nlok5923, I'd like to take this up, please assign :)

**Comment by nlok5923** [comment]
@naveen8801 GFI 👍

**Comment by jatinjain001** [comment]
I would like to work on it , Please let me know

**Comment by nlok5923** [comment]
@jatinjain001 this issue has been already assigned to @naveen8801 you can search for other issues.
