### ISSUE TITLE
Add a button to download the form

### ISSUE THREAD

**Issue by RohanKeshri87** [QAZIMAAZARSHAD/Voters-Registration-Portal#23]
If a voter wants then he/she can download and prints the keep it for reference

**Comment by QAZIMAAZARSHAD** [comment]
Nice Idea,

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by urvashiparashar** [comment]
I want to work upon this. Please assign me this
@QAZIMAAZARSHAD

**Comment by sameer2403** [comment]
I would like to work on this issue.Please assign me

**Comment by royalleads15** [comment]
@QAZIMAAZARSHAD Sir I am also interested , kindly assign me too.
