### ISSUE TITLE
Improve padding in help page footer

### ISSUE THREAD

**Issue by puneetkaur2929** [QAZIMAAZARSHAD/Voters-Registration-Portal#230]
hey @QAZIMAAZARSHAD 
As you can see in screenshot attached below that copyright section is not visible for voter login page .

I am interested to fix it.
Kindly assign this issue to me under LGM SOC '21
![Screenshot (34)](https://user-images.githubusercontent.com/80326308/122813373-84630d00-d2f0-11eb-91f3-dccaa135ae43.png)

**Comment by QAZIMAAZARSHAD** [comment]
@puneetkaur2929 this issue has been fixed check again.

**Comment by QAZIMAAZARSHAD** [comment]
But you can do one thing 
![image](https://user-images.githubusercontent.com/56196640/122864574-83f36200-d342-11eb-9a8f-9d0d114e3fbb.png)

This is the screenshot of the help page, as you can see padding in the copyright line is more compared to other footers. Fix this.
