### ISSUE TITLE
To prevent Show Password from hiding

### ISSUE THREAD

**Issue by puneetkaur2929** [QAZIMAAZARSHAD/Voters-Registration-Portal#232]
Hey @QAZIMAAZARSHAD 

In the voter Sign-Up page show password is hiding behind other options.
I am interested to work on this issue under LGM SOC '21
Kindly assign this issue to me 
![Screenshot (35)](https://user-images.githubusercontent.com/80326308/122814707-33541880-d2f2-11eb-97f0-bde01b7c852b.png)

**Comment by QAZIMAAZARSHAD** [comment]
![image](https://user-images.githubusercontent.com/56196640/122864960-2a3f6780-d343-11eb-889d-f0d53afad306.png)

Their is no such issue, may be you have zoomed in or out your window screen.
