### ISSUE TITLE
Overlapping textbox and Reset/Submit button for mobile view

### ISSUE THREAD

**Issue by anjali481** [QAZIMAAZARSHAD/Voters-Registration-Portal#239]
![image](https://user-images.githubusercontent.com/55936581/123098098-68757d80-d44e-11eb-9b82-ac8697abf1a1.png)

In mobile view, textbox and buttons are getting overlapped.

**Comment by anjali481** [comment]
I am interested to fix it.

**Comment by Gauravkain** [comment]
Hello , I want to contribute on this issue.

**Comment by nlok5923** [comment]
@Gauravkain this issue is already assigned to @anjali481 you can look for some other issues, thanks

**Comment by aashimawadhwa** [comment]
If someone is not working. Can I work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> If someone is not working. Can I work on this issue.

This issue is already assigned.
