### ISSUE TITLE
Display pictures of uploaded documents

### ISSUE THREAD

**Issue by Zhong-Shan-Hui** [QAZIMAAZARSHAD/Voters-Registration-Portal#24]
By displaying the photo, the person can check whether the correct photo is uploaded or not.

**Comment by QAZIMAAZARSHAD** [comment]
Nice idea,
But do it for all documents, display photos of all the uploaded documents.

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Fine @Zhong-Shan-Hui.

Wait till I review your PR.
