### ISSUE TITLE
Fix the footer in all pages

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#241]
The red circle indicates a bug, green circle indicates correct alignment. Check these on all pages.

![Screenshot (158)](https://user-images.githubusercontent.com/56196640/123217794-98715f00-d4e8-11eb-8940-c970f424618a.png)
![Screenshot (159)](https://user-images.githubusercontent.com/56196640/123217816-9ad3b900-d4e8-11eb-8280-02d953b09599.png)

Remove large spaces in the footer in mobile view.
![image](https://user-images.githubusercontent.com/56196640/123218272-23eaf000-d4e9-11eb-9f57-eb62c8496678.png)

**Comment by Albert-Jokelin** [comment]
I can work on this

**Comment by Namangujral1** [comment]
Can i work on this? Please assign it to me

**Comment by Albert-Jokelin** [comment]
Hey! I'm still working on it, will create a PR in a few hours

**Comment by QAZIMAAZARSHAD** [comment]
> Can i work on this? Please assign it to me

Already resolved by @Albert-Jokelin.

**Comment by skpandey885** [comment]
Hey, Can You Assign This Issue To Me If Any Bug is Left!
Under LGMSoC'21

**Comment by QAZIMAAZARSHAD** [comment]
> Hey, Can You Assign This Issue To Me If Any Bug is Left!
> Under LGMSoC'21

Someone is already working on it.
