### ISSUE TITLE
Print icon in mobile view

### ISSUE THREAD

**Issue by RiyaGupta89** [QAZIMAAZARSHAD/Voters-Registration-Portal#247]
## Describe the bug
![mobileview](https://user-images.githubusercontent.com/72425181/123362606-94981800-d58e-11eb-8825-706f84c42e92.png)
The print icon is not in place at 360px wide screens.

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 there is no such issue.

![image](https://user-images.githubusercontent.com/56196640/123363452-31a78080-d590-11eb-8f86-f5491dd25dc2.png)
