### ISSUE TITLE
Add asterisk to the mandatory fields in sign-up page

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#251]
While registration it would be good if user is aware about which fields are mandatory to fill

add a little red *(asterisk) with the label of required field 

Mandatory fields are:
First name
Last name
Email address
Password
confirm password

![image](https://user-images.githubusercontent.com/56120084/123419644-1a8c8100-d5d8-11eb-95e7-8c1a6b60b93b.png)

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD could you please add all the mandatory fields information of registration page to the issue description.

**Comment by QAZIMAAZARSHAD** [comment]
Mandatory fields already have asterisks.

**Comment by QAZIMAAZARSHAD** [comment]
@nlok5923  ???

**Comment by nlok5923** [comment]
> @nlok5923 ???

this issue is for registration page.

**Comment by anushruti11** [comment]
Can I work on this issue?
