### ISSUE TITLE
Migrate from conventional JS alert to Swal

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#252]
## Is your feature request related to a problem? Please describe.
Currently for all the notification/warning/alerts purposes we are using javascript inbuilt alert module. which is kinda looks very conventional with plain UI.

## Describe the solution you'd like
Migration to swal(sweetalert) javascript module. Sweet alert module in itself profile much simple methods and good looking modals 

for more info refer [here](https://sweetalert.js.org/guides/)

## Additional context
Current alert:
![image](https://user-images.githubusercontent.com/56120084/123415287-aac7c780-d5d2-11eb-96f3-421a959a2960.png)

Sweet alert:
![image](https://user-images.githubusercontent.com/56120084/123415383-cd59e080-d5d2-11eb-9001-562504a679e6.png)

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD please take a look.

**Comment by princeprag** [comment]
@QAZIMAAZARSHAD can i please work on this issue?

**Comment by nlok5923** [comment]
@princeprag  GFI 👍

**Comment by princeprag** [comment]
@nlok5923 fields such as state, city & zipcode are not asterisked.. shall I remove them from the validation check, currently they are not supposed to be left empty!

**Comment by nlok5923** [comment]
@princeprag I think you can do that @QAZIMAAZARSHAD please confirm.

**Comment by princeprag** [comment]
I think in a real word scenario, these demographic fields need to be mandatory.. @QAZIMAAZARSHAD !!

**Comment by QAZIMAAZARSHAD** [comment]
> I think in a real word scenario, these demographic fields need to be mandatory.. @QAZIMAAZARSHAD !!

Yes, fine.

Add asterisks to other fields as well.

**Comment by nlok5923** [comment]
closing as #255  addressed it

**Comment by nlok5923** [comment]
closing this issue as #255 addressed it.
