### ISSUE TITLE
Validate sign-up page inputs

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#257]

**Comment by anushruti11** [comment]
I would like to work on this issue.

**Comment by Srit20** [comment]
i would like to work on this issue please assign me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> i would like to work on this issue please assign me @QAZIMAAZARSHAD

Already assigned.

Look for some other issues.
