### ISSUE TITLE
Add captcha with speaker on Sign-up page too

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Voters-Registration-Portal#261]
Add captcha with speaker on Sign-up page too<br>
![captcha](https://user-images.githubusercontent.com/56637948/123521776-67ef1800-d6d6-11eb-8ec1-0b78dac3ccfd.jpg)

**Comment by nlok5923** [comment]
@royalleads15 @QAZIMAAZARSHAD i think we should break this issue in two issue one for adding captcha and another for adding voice inputs feature.

**Comment by nlok5923** [comment]
also @royalleads15 can you please let me know are you gonna using any api for voice captcha or implement it with using built in javascript media module ?

**Comment by royalleads15** [comment]
Sir @QAZIMAAZARSHAD instead of breaking it into 2 issue I request to increase level of issue.

**Comment by QAZIMAAZARSHAD** [comment]
> Sir @QAZIMAAZARSHAD instead of breaking it into 2 issue I request to increase level of issue.

Sure,

Remember the label in issue is always temporary and can be decreased or increased considering the efforts, number of lines of code, cleanliness of code, etc.
