### ISSUE TITLE
background video of welcome page

### ISSUE THREAD

**Issue by Saumya-Patel** [QAZIMAAZARSHAD/Voters-Registration-Portal#263]
I think the website will look more effective if we replace the background video of foreigner in home page by some Indian stuff, because the website is dedicated to INDIA only.

**Comment by QAZIMAAZARSHAD** [comment]
@Saumya-Patel this issue is already open https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/145.

You can work on that, ping me to assign you.
