### ISSUE TITLE
Design a creative logo for this website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#265]
![image](https://user-images.githubusercontent.com/56196640/123529251-195c7080-d70c-11eb-91d7-92468772ae04.png)

Design something like the above image.
Also, add a catchy desi slogan.

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD i think you should increase the level of this issue to level2 at least because getting approval over designed logo is really hectic task i am expecting the designing logo will involve many iterations from contributor side.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD i think you should increase the level of this issue to level2 at least because getting approval over designed logo is really hectic task i am expecting the designing logo will involve many iterations from contributor side.

I have labeled it as zero because there are many logo maker websites and apps, and it takes just a few minutes to create any design.
And it cannot be determined whether the contributor has used an app or has put in efforts to completely design it using photoshop or illustrator.

**Comment by skpandey885** [comment]
Hey, Can I Work On This Issue Under LGMSoC'21?

**Comment by nlok5923** [comment]
@skpandey885 GFI 👍

**Comment by skpandey885** [comment]
Thanks For Assigning! I Will Soon Make The Changes And Update You!

**Comment by skpandey885** [comment]
Hey! Can You Tell Me The Following Things-
1. What should Be The name of The logo I mean What Should Be Written On it? "Adhaar"? Or Something Related To Vote!!!
2. I have To Send The Logo Here? Because I Don't See Any Place In the website To fit In The logo!
@QAZIMAAZARSHAD  Help Me Sir!

**Comment by QAZIMAAZARSHAD** [comment]
Name - Voters Registration Portal
You can also add any catchy desi slogan

And show the logo here first.

For PR, create a logo folder in the images folder and just add the logo file there.

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD i think we should only involve the initials of project name to the logo

**Comment by QAZIMAAZARSHAD** [comment]
Okk, try both initials and full name, we'll accept the one which looks good.

**Comment by skpandey885** [comment]
@QAZIMAAZARSHAD Sir! How's This?

![image](https://user-images.githubusercontent.com/78532081/123655610-be7e6280-d84c-11eb-90a5-45c227ed44e6.png)

**Comment by nlok5923** [comment]
@skpandey885 it would be good if you can present 2-3 logos so that we can normalise parameters for best logo selection.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Sir! How's This?
> 
> ![image](https://user-images.githubusercontent.com/78532081/123655610-be7e6280-d84c-11eb-90a5-45c227ed44e6.png)

Cool.

**Comment by QAZIMAAZARSHAD** [comment]
> @skpandey885 it would be good if you can present 2-3 logos so that we can normalise parameters for best logo selection.

@skpandey885 if you have any more ideas gon ahead.

**Comment by skpandey885** [comment]
@nlok5923 @QAZIMAAZARSHAD  So We Are Finalizing This One Or You Want To See More?

**Comment by QAZIMAAZARSHAD** [comment]
> @nlok5923 @QAZIMAAZARSHAD So We Are Finalizing This One Or You Want To See More?

@skpandey885 if you have any more ideas go ahead.

**Comment by skpandey885** [comment]
Ok! I will show You 2-3 More pieces Then Will Pick One And Go Ahead!

**Comment by skpandey885** [comment]
So, I Have Made These Logos! Click On The Links:

https://mail.google.com/mail/u/0?ui=2&ik=c74cea5476&attid=0.1&permmsgid=msg-a:r-3885467505317949018&th=17a5ff8dad14f274&view=att&disp=safe&realattid=17a5ff796faccd830e71

https://mail.google.com/mail/u/0?ui=2&ik=c74cea5476&attid=0.3&permmsgid=msg-a:r-3885467505317949018&th=17a5ff8dad14f274&view=att&disp=safe&realattid=17a5ff8c85fb2943dd93

https://mail.google.com/mail/u/0?ui=2&ik=c74cea5476&attid=0.2&permmsgid=msg-a:r-3885467505317949018&th=17a5ff8dad14f274&view=att&disp=safe&realattid=17a5ff7972e8a21481e2

**Comment by QAZIMAAZARSHAD** [comment]
Great work @skpandey885.

Now you can make PR.

Just create a logo folder in the Images folder and these 3 files in the logo folder.

**Comment by QAZIMAAZARSHAD** [comment]
@nlok5923 and @skpandey885 one of these will be used on the website, which one you suggest?

**Comment by nlok5923** [comment]
the middle one looks good to me.

**Comment by skpandey885** [comment]
I Think the last One Is good!  The One With "Apka Hak Apki Taakat"
