### ISSUE TITLE
Accept AADHAR number and VOTER-ID number from user 

### ISSUE THREAD

**Issue by Vedant-Jayesh-Oza** [QAZIMAAZARSHAD/Voters-Registration-Portal#27]
Hello sir, I am LGM-SOC'21 participant 

Now-a-days in every online form that we fill in any domain such as passport, banking etc. The portal always asks for Adhaar number of the applicant and as this is a Voter registration portal so we should also accept Voter ID of the user 

So in the mandatory specification section we should ask for voter's adhaar number and Voter ID number 

I am LGM-SOC'21 participant so I would like to work on this issue please assign this issue to me

**Comment by QAZIMAAZARSHAD** [comment]
@Vedant-Jayesh-Oza this is a form for enrollment in the electoral roll (means an application for Voter Id) so you cannot ask for voter Id.

Also, we have a section for uploading supported documents so the Adhaar card can be used as address and age proof.
Also, in general, voter id can be generated without adhaar card using other Id proofs.
There is no need to include the Adhaar card in the mandatory specifications section.

You can look for any other issue, open new issues or suggest new features, etc.

**Comment by Vedant-Jayesh-Oza** [comment]
Ok fair enough 👍
