### ISSUE TITLE
FormCorrection Page not fetching list of Districts..

### ISSUE THREAD

**Issue by princeprag** [QAZIMAAZARSHAD/Voters-Registration-Portal#270]
## Describe the bug
The district dropdown in the formCorrection is Empty.
![Screenshot (105)](https://user-images.githubusercontent.com/51314718/123546219-51e66380-d779-11eb-95d8-afc8c3824213.png)

## To Reproduce
1. Method 1 - At first we should have a State field. On choosing the state the list of all districts should come
2. Method 2- We can use some API to automatically fill the State & District fields on entering pinCode, it might be a little difficult but I would like to give it a try :smiley:

## Environment (please complete the following information):
 - OS: Windows
 - Browser: Chrome

**Comment by princeprag** [comment]
@QAZIMAAZARSHAD , please have a look and let me know if we can go with Method 2?

**Comment by nlok5923** [comment]
@princeprag i think you should keep app uniform so you can go with method 1 please confirm @QAZIMAAZARSHAD

**Comment by princeprag** [comment]
@nlok5923 , yep! For maintaining uniformity.. Method 1 is better!
