### ISSUE TITLE
Footer link should redirect to actual sites

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#271]
## Describe the bug
- Currently the footer links under government of india section redirect to #

## To Reproduce
1. Head over to footer 
2. Click on any link under goverment of india section

## Expected behavior

- It should redirect to actual sites

## Logs
this links i am talking about
![image](https://user-images.githubusercontent.com/56120084/123547288-ccb17d80-d77d-11eb-92db-e31302e0eb18.png)

## Environment (please complete the following information):
 - OS: all
 - Browser: all

**Comment by royalleads15** [comment]
Sir @QAZIMAAZARSHAD I would like to do work on it
