### ISSUE TITLE
Improve Password Verification

### ISSUE THREAD

**Issue by arnab8335** [QAZIMAAZARSHAD/Voters-Registration-Portal#273]
Currently, the password accepts only 6 characters,

Improve the constraints.
Minimum length - 8 characters
Must include at least one uppercase alphabet.
Must be alphanumeric.
Must include at least one special character.

Do this in Login, Sign-up, and Forget password page.

**Comment by QAZIMAAZARSHAD** [comment]
Do it in all three pages - login, sign up and forgot password page.

**Comment by arnab8335** [comment]
@QAZIMAAZARSHAD should I add only the password files or can you tell me what to add
I have worked on the issue and completed it.

**Comment by arnab8335** [comment]
![WhatsApp Image 2021-07-03 at 12 50 53 PM](https://user-images.githubusercontent.com/69088399/124346584-52f61580-dbfd-11eb-946a-c15e86e0a768.jpeg)

**Comment by QAZIMAAZARSHAD** [comment]
Only work on password par.

Instead of a password of 6 characters, apply constraints like at least 1 upper case, special character, number.

**Comment by arnab8335** [comment]
@QAZIMAAZARSHAD I have done it

**Comment by arnab8335** [comment]
Could you please check

**Comment by QAZIMAAZARSHAD** [comment]
> Could you please check

provide a demo link.

**Comment by arnab8335** [comment]
@QAZIMAAZARSHAD  https://arnab8335.github.io/password_check/ Please check it out and let me know

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD https://arnab8335.github.io/password_check/ Please check it out and let me know

@arnab8335 what should I do with this?

Implement this on the website then show. Everything should be the same on the website just change the message "Password length should be 6" and correct the password constraint on all three pages.

**Comment by arnab8335** [comment]
![image](https://user-images.githubusercontent.com/69088399/124985415-032da900-e058-11eb-966c-8d1a446443b9.png)

**Comment by arnab8335** [comment]
@QAZIMAAZARSHAD  is it fine

**Comment by QAZIMAAZARSHAD** [comment]
No not like this.

Change the prompt 
![image](https://user-images.githubusercontent.com/56196640/125020389-62aaa980-e096-11eb-9586-e7ba3de13e6c.png)

**Comment by arnab8335** [comment]
@QAZIMAAZARSHAD I am unable to do that I have implemented what I have thought about but its currently not feasible for me to do this

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I am unable to do that I have implemented what I have thought about but its currently not feasible for me to do this

@arnab8335 I didn't get you.


You have to only make few modifications in JavaScript code in the login, signup, and forget pass page.
You can take help from @nlok5923.

**Comment by arnab8335** [comment]
@nlok5923 please help me to fix the code

**Comment by nlok5923** [comment]
@arnab8335 please create a pr so that i can review and suggest the code changes.

**Comment by dilroseR** [comment]
Can i get this one to work upon?

**Comment by nlok5923** [comment]
GFI 👍 @dilroseR

**Comment by dilroseR** [comment]
> GFI 👍 @dilroseR

on which page should i implement this? and what all?

**Comment by QAZIMAAZARSHAD** [comment]
> > GFI 👍 @dilroseR
> 
> on which page should i implement this? and what all?

Currently, the password accepts only 6 characters,

Improve the constraints.
Minimum length - 8 characters
Must include at least one uppercase alphabet.
Must be alphanumeric.
Must include at least one special character.

Do this in Login, Sign-up, and Forget password page.

**Comment by QAZIMAAZARSHAD** [comment]
Take one issue at a time.

Resolve the other one first.

**Comment by dilroseR** [comment]
> Take one issue at a time.
> 
> Resolve the other one first.

ok no issues i'll finish that then i'll move on to this issue

**Comment by dilroseR** [comment]
> > > GFI 👍 @dilroseR
> > 
> > 
> > on which page should i implement this? and what all?
> 
> Currently, the password accepts only 6 characters,
> 
> Improve the constraints.
> Minimum length - 8 characters
> Must include at least one uppercase alphabet.
> Must be alphanumeric.
> Must include at least one special character.
> 
> Do this in Login, Sign-up, and Forget password page.

what should be the max length of the password?

**Comment by QAZIMAAZARSHAD** [comment]
16

**Comment by dilroseR** [comment]
> 16

can i make a pr for this till mentors reply back me on the other issue?

**Comment by QAZIMAAZARSHAD** [comment]
Sure. Do it as you wish.
