### ISSUE TITLE
Improve login/signup/forget password page design

### ISSUE THREAD

**Issue by skpandey885** [QAZIMAAZARSHAD/Voters-Registration-Portal#279]
Feature: CSS Of Login and Registration Portal Can Be Modified!
Example:(New Colors, Hover Effects, Better Fonts Can Improve The Look Of The Website!)

**Comment by padmajabhol** [comment]
Is this still open?

**Comment by skpandey885** [comment]
> Is this still open?

Hey! This Issue Is Open But Has Been Assigned to Me and I am Working on it! So Try to Find Some News Bugs Yourself and Work On Them! Thanks For Your Concern!

**Comment by QAZIMAAZARSHAD** [comment]
Accepeted. Points awarded.

**Comment by skpandey885** [comment]
> Accepeted. Points awarded.

Bhaiya, How can I see All points earned?
and Will My name be Added In Contributers List?

**Comment by QAZIMAAZARSHAD** [comment]
> > Accepeted. Points awarded.
> 
> Bhaiya, How can I see All points earned?
> and Will My name be Added In Contributers List?

Organizers are working on the leaderboard.
Also, it is advisable to always keep a count of all your PR's and levels so in case of any mistake by project admin and organizers you can correct it. If you have kept a track of all your PR's then you can calculate your score yourself.

Yes, your name has automatically been included in the contributor's list of that project if you have made any contributions.
