### ISSUE TITLE
Add dark/light mode to website

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Voters-Registration-Portal#28]
Dark and light mode must be added in portal so that user can access it as he/she wants.

**Comment by QAZIMAAZARSHAD** [comment]
Nice idea,

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by V-Yeshwanth** [comment]
I would like to work on this issue !!

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue !!

Go ahead.
Keep in mind the first PR with better design will be accepted.

**Comment by mdinesh124** [comment]
Please assign me this issue. I would be happy to contribute in it as a part of LGMSOC

**Comment by 1anshu-56** [comment]
I want to work on this issue can you please assign it to me as I have previous experience with this issue.

**Comment by 1anshu-56** [comment]
Thanks for assigning @QAZIMAAZARSHAD

**Comment by nitishapiplani** [comment]
I would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue

Already assigned to others,
