### ISSUE TITLE
Improve header section

### ISSUE THREAD

**Issue by ayshi028** [QAZIMAAZARSHAD/Voters-Registration-Portal#281]
## To Reproduce
1. The logo of the "Satyamev Jayata" should be more left.
2. The header portion should be more attractive so that it looks good.
3.  All the icons should be placed at the right top corner so that it will be accessible from that position and one can go to that desired location. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by QAZIMAAZARSHAD** [comment]
@ayshi028 what improvements you are suggesting?

**Comment by ayshi028** [comment]
The Satyamev Jayate Icon will be more towards the left and the header portion will be more attractive and will build a div with toogle in order to create smooth scrolling through pages

**Comment by QAZIMAAZARSHAD** [comment]
@ayshi028 this issue already open #223.
