### ISSUE TITLE
Improve the show password method in login, sign-up, and forget password page

### ISSUE THREAD

**Issue by tjanhvi** [QAZIMAAZARSHAD/Voters-Registration-Portal#282]
Remove the show password checkbox and add icons in the input fields.
Do this on the login, sign-up, and forget password page.

![image](https://user-images.githubusercontent.com/56196640/126274591-1ab1e226-71f0-4379-8645-15b918e54142.png)

**Comment by QAZIMAAZARSHAD** [comment]
@tjanhvi didn't get your idea?

Explain again, please.

**Comment by tjanhvi** [comment]
In the form, there is a checkbox to show the entered password so i want to remove it and mention it in the input box as an icon that shows the entered password.

**Comment by yuhang0627** [comment]
Hi, can you assign this to me? I have an idea to improve the show password button with a eye logo attached at below when user click the eye button then the password become visible and I can add a password strength at the user sign up and forget password page.
![hidden](https://user-images.githubusercontent.com/86589370/126510250-ff455438-c2de-4276-9707-8a39f0ec3734.png)

**Comment by QAZIMAAZARSHAD** [comment]
> Hi, can you assign this to me? I have an idea to improve the show password button with a eye logo attached at below when user click the eye button then the password become visible and I can add a password strength at the user sign up and forget password page.
> ![hidden](https://user-images.githubusercontent.com/86589370/126510250-ff455438-c2de-4276-9707-8a39f0ec3734.png)

Under DCP or LGMSoC?

**Comment by yuhang0627** [comment]
> > Hi, can you assign this to me? I have an idea to improve the show password button with a eye logo attached at below when user click the eye button then the password become visible and I can add a password strength at the user sign up and forget password page.
> > ![hidden](https://user-images.githubusercontent.com/86589370/126510250-ff455438-c2de-4276-9707-8a39f0ec3734.png)
> 
> Under DCP or LGMSoC?

Nope for both

**Comment by QAZIMAAZARSHAD** [comment]
Fine.
