### ISSUE TITLE
Validate user inputs in sign up page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#286]

**Comment by princeprag** [comment]
@QAZIMAAZARSHAD you can assign me!

**Comment by ujju20** [comment]
Is this issue solved by the assignee or can I work on this issue?

**Comment by purohitmansi** [comment]
I want to solve this.
please do assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
> I want to solve this.
> please do assign this to me.

Already assigned.

**Comment by ujju20** [comment]
Can you give a hint of solving this issue because input fields like email and mobile number are already validated?

**Comment by QAZIMAAZARSHAD** [comment]
@ujju20 this form got submitted.
![image](https://user-images.githubusercontent.com/56196640/125229953-7869da00-e2f5-11eb-87c0-bba418a4023f.png)


See first name, last name, email, city are wrong still it is getting submitted.
You have to work on this.

**Comment by ujju20** [comment]
Ok got it.

**Comment by QAZIMAAZARSHAD** [comment]
@princeprag and @ujju20  any updates?

**Comment by puneetkaur2929** [comment]
Hey @QAZIMAAZARSHAD 
I am interested to work on this issue under LGM SOC 21

**Comment by puneetkaur2929** [comment]
@QAZIMAAZARSHAD 
I am working on this issue but when after filling all details it is not getting sign-up. Can you suggest me ways to correctly use it?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD
> I am working on this issue but when after filling all details it is not getting sign-up. Can you suggest me ways to correctly use it?
> I mean how to sign-up .

Can't tell without seeing the code.
I suggest, make a PR then we will discuss.

**Comment by puneetkaur2929** [comment]
Hey @QAZIMAAZARSHAD 
I am trying to push changes on github but this message id being displayed .
how to correct it?
![Screenshot (66)](https://user-images.githubusercontent.com/80326308/127095866-79782a96-7f44-4333-a059-ef7dc1c88020.png)

**Comment by QAZIMAAZARSHAD** [comment]
@puneetkaur2929 I think you were trying to push changes in my repo. You can't do that.

Push changes in your repo then make PR to my repo.

**Comment by puneetkaur2929** [comment]
@QAZIMAAZARSHAD 
I am trying to push in new branch , but the same issue still persists.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD
> I am trying to push in new branch , but the same issue still persists.

Share screenshot.

Search error message on google you will get the solution.

**Comment by ayush-dudhani** [comment]
I made changes required under this issue..Can you assign me this task ?
