### ISSUE TITLE
Welcome page

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Voters-Registration-Portal#29]
We can also show user a popup containing of documents required for registration so that user can come along with all document required for registration .

**Comment by QAZIMAAZARSHAD** [comment]
> We can also show users a popup containing documents required for registration so that users can come along with all documents required for registration.

@royalleads15 this issue is already open, see issue number https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/6.

You can look for any other issue.
