### ISSUE TITLE
Spacing in the footer

### ISSUE THREAD

**Issue by srisatya1197** [QAZIMAAZARSHAD/Voters-Registration-Portal#294]
## Describe the bug
![Voter Login - Google Chrome 30-06-2021 15_17_30_LI (2)](https://user-images.githubusercontent.com/78905067/123941516-daeade00-d9b7-11eb-9c94-211b12c5a8b2.jpg)

The space between policies and government of india is more. I want to align them in same way.

**Comment by QAZIMAAZARSHAD** [comment]
Then there will be more space in the right corner.

Try to add one more column, something between these two sections.

**Comment by srisatya1197** [comment]
Done !!

**Comment by srisatya1197** [comment]
@QAZIMAAZARSHAD  Just I want to clear that I'll be inactive on github for a week(sem exams). I want to tell that if it's ok then will complete this after a week.

**Comment by QAZIMAAZARSHAD** [comment]
fine
