### ISSUE TITLE
Make captcha reload functionable

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#3]
![image](https://user-images.githubusercontent.com/56196640/120430948-665f5800-c395-11eb-8b7d-fb8638d397a6.png)

It should load a random captcha when clicking reload button.

**Comment by shivshankar9** [comment]
I want to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Kartikey0205** [comment]
May I work on this @QAZIMAAZARSHAD ?

**Comment by utkarshgoel10** [comment]
Please assign this issue to me @QAZIMAAZARSHAD
