### ISSUE TITLE
Add a Demo/Guest Login

### ISSUE THREAD

**Issue by Akshu-on-github** [QAZIMAAZARSHAD/Voters-Registration-Portal#300]
## Is your feature request related to a problem?
There's no guest login/dummy credentials - if I wanted to take a look at the UI, I need to provide an email and password. If I provide a random/burn email, it may affect the project's database...

## Describe the solution you'd like
Create a separate login method that either bypasses the login criteria (or) logs in with dummy credentials.
(Example: ```Alex Doe, alex.doe@example.com``` that can easily be filtered out from the database)

## Additional context
Demo/guest logins greatly improve the UX:
- They allow developers to focus on testing the project without worrying about sharing PII
- They allow a 'test run' or 'tutorial' for newcomers to the project

If all is in order, I'd like to take this up for LGM SoC 2021

**Comment by QAZIMAAZARSHAD** [comment]
@Akshu-on-github there is no backend in this project.

E-mail id will not be stored anywhere so no harm to the user's privacy or projects database(not exists).



But login as a guest is a nice idea, go ahead.

**Comment by Akshu-on-github** [comment]
Thank you for helping me contribute to this project!
