### ISSUE TITLE
Add website logo in the footer

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#302]
Add the logo inside the box

![Screenshot (7)](https://user-images.githubusercontent.com/56196640/124079841-48097c80-da67-11eb-9a17-5da0cdd0053a.png)

Use this logo -> Voters-Registration-Portal/Images/Logo/logo1.jpg

https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/blob/master/Images/Logo/logo1.jpg

**Comment by GaurPeeyush** [comment]
I'd like to work on this issue.
Kindly assign

**Comment by purohitmansi** [comment]
Please assign this to me.

**Comment by purohitmansi** [comment]
Thank you for assigning.

**Comment by Croooook** [comment]
Can You please assign this to me? I can work on this. This will be my first issue for open source community to be allowed to work upon.

**Comment by kanak22** [comment]
@purohitmansi any updates till now?

**Comment by purohitmansi** [comment]
No, I am not able to. U can go ahead with the issue.

**Comment by kanak22** [comment]
okay then @Croooook go ahead :)
