### ISSUE TITLE
Shift the dark/light mode toggle button at the bottom left of footer

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#303]
![Screenshot (8)](https://user-images.githubusercontent.com/56196640/124080856-76d42280-da68-11eb-803f-86cbaae604a9.png)

Also, try to change the design of the button.

Do the changes on all pages.

**Comment by royalleads15** [comment]
I would Like to work on it Sir

**Comment by QAZIMAAZARSHAD** [comment]
Also, increase the size of the logo in the header as on the help page.

**Comment by nik464** [comment]
I would also like to work on this issue. Please assign me . I am from lgm soc.
