### ISSUE TITLE
Replace Tiranga image in header with the logo

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#304]
Use this logo -> Voters-Registration-Portal/Images/Logo/logo1.jpg

https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/blob/master/Images/Logo/logo1.jpg

**Comment by abhishekkumar08** [comment]
Can I work on this? @QAZIMAAZARSHAD
