### ISSUE TITLE
Captcha code overflowing from the box

### ISSUE THREAD

**Issue by Soham-Official** [QAZIMAAZARSHAD/Voters-Registration-Portal#306]
## Describe the bug
In the registration portal's captcha section the captcha code is overflowing when a big font is coming as captcha. 

## To Reproduce
1. Go to voter Registration portal.
2. Scroll down to captcha section.
3. Change the captcha by clicking the button below it.
4. Eventually it can be seen that many code is overflowing the box.

## Expected behavior
The captcha box should be responsive to the captcha size.

## Environment (please complete the following information):
 - OS: Windows 10
 - Browser: Google Chrome

## Additional context
![image](https://user-images.githubusercontent.com/54814610/124098813-878d9400-da7a-11eb-8fd6-005e264f25c9.png)
![image](https://user-images.githubusercontent.com/54814610/124098843-8d837500-da7a-11eb-9f9a-67cdba401242.png)
![image](https://user-images.githubusercontent.com/54814610/124098872-9411ec80-da7a-11eb-9bdd-f49df26f3bde.png)

**Comment by Soham-Official** [comment]
Please assign me to this issue under LGMSOC'21

**Comment by QAZIMAAZARSHAD** [comment]
Check again.

Must be some issue with your window size (zoom in /zoom out).

There is no such issue.
![image](https://user-images.githubusercontent.com/56196640/124099199-e81cd100-da7a-11eb-887d-d202130b5945.png)

**Comment by Soham-Official** [comment]
@QAZIMAAZARSHAD I think your window size is of shorter width , but if you open it with large screens(pc)..you can detect the error.
![image](https://user-images.githubusercontent.com/54814610/124102865-5a42e500-da7e-11eb-8fab-a9ebac8765fe.png)
as you can see ,zoom is at the default!
so please reconsider and check it using larger screen devices.

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

Fix the issue.

**Comment by royalleads15** [comment]
Check this problem in signup page too.
