### ISSUE TITLE
Home.html has a bug.

### ISSUE THREAD

**Issue by codingninja11** [QAZIMAAZARSHAD/Voters-Registration-Portal#312]
## Describe the bug
Some code is visible on top of the page @QAZIMAAZARSHAD 
![image](https://user-images.githubusercontent.com/64359203/124242001-ebc35d00-db39-11eb-96cd-62785faff7be.png)

**Comment by QAZIMAAZARSHAD** [comment]
@codingninja11 check again.
![image](https://user-images.githubusercontent.com/56196640/124242383-507eb780-db3a-11eb-8fbe-8e66e93fae26.png)

**Comment by codingninja11** [comment]
Yes Its fine now.
