### ISSUE TITLE
Create a submission accepted page

### ISSUE THREAD

**Issue by menakinako** [QAZIMAAZARSHAD/Voters-Registration-Portal#316]
I would like to  add a thank you page after the successful submission of the form. 
Here in this thank you page we can add the form_correction page link so that anyone who feels that he/she has entered wrong data can make changes even after form submission.

**Comment by QAZIMAAZARSHAD** [comment]
@menakinako we cannot call it a thank you page because it is an application form.

Create a page that says form successfully submitted, your voter id will be generated within a few days. Create a page like that.
