### ISSUE TITLE
Create a feedback page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#319]
![Screenshot (12)](https://user-images.githubusercontent.com/56196640/124357321-7db18f80-dc38-11eb-870d-5f867fb66ffd.png)

Link it with all pages.

Refer to a few websites for ideas for the feedback page.

**Comment by skpandey885** [comment]
Hey Bhaiya! I am Interested Can You Explain a bit more! I Can't Understand!

**Comment by akshitaWaldia** [comment]
I would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
@skpandey885 the feedback page can be like a form.

Asking questions like:
Any difficulty you faced?
How was the online experience?
Do you still prefer applying offline?
Any feature you request to be included on the website?
Which device did you use?
Any bug/typo or wrong information on the website?

**Comment by QAZIMAAZARSHAD** [comment]
How to design, include what features, which questions are totally up to you, but header and footer must be the same.

**Comment by skpandey885** [comment]
Ok bhaiya! I will contact You if i face Any Issue Or Have any doubt!

**Comment by skpandey885** [comment]
> How to design, include what features, which questions are totally up to you, but header and footer must be the same.

Bhaiya The Form Should also be linked to backend? I don't know about backend /database

**Comment by QAZIMAAZARSHAD** [comment]
> > How to design, include what features, which questions are totally up to you, but header and footer must be the same.
> 
> Bhaiya The Form Should also be linked to the backend? I don't know about backend /database

The website doesn't have any backend right now.

Just create a frontend design like the rest of the website.

**Comment by skpandey885** [comment]
> > > How to design, include what features, which questions are totally up to you, but header and footer must be the same.
> > 
> > 
> > Bhaiya The Form Should also be linked to the backend? I don't know about backend /database
> 
> The website doesn't have any backend right now.
> 
> Just create a frontend design like the rest of the website.

Ok Bhaiya! I'll do it!
Thanks

**Comment by stellashank** [comment]
Sir can u assign me this issue

**Comment by QAZIMAAZARSHAD** [comment]
> Sir can u assign me this issue

This one is already assigned. You can work on this one https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/328.
