### ISSUE TITLE
Add help section 

### ISSUE THREAD

**Issue by royalleads15** [QAZIMAAZARSHAD/Voters-Registration-Portal#32]
Help section must be added in header or footer so that if anyone find difficulty in registration process he/she can acess it .

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead,

But don't add this section to the main page, create a separate page. Add the link to that page in the footer.

**Comment by harshita9621** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by QAZIMAAZARSHAD** [comment]
> Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Sumit11081996** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by QAZIMAAZARSHAD** [comment]
> Hii, I would like to work on this issue as an LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.
Since many contributors are willing to resolve this issue, keep in mind the best design/solution will be accepted.

**Comment by QAZIMAAZARSHAD** [comment]
Fine @royalleads15.
Wait till I review your PR.

**Comment by aditya687** [comment]
I can add help section to get the customer feedback by giving a wonderful design with icons at the footer. Please assign me this issue  @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
> I can add help section to get the customer feedback by giving a wonderful design with icons at the footer. Please assign me this issue @QAZIMAAZARSHAD

@aditya687 this issue has already been resolved.
If you want to improve you can open new issues after I merge this PR.

**Comment by QAZIMAAZARSHAD** [comment]
@harshita9621 and @royalleads15 you guys were not able to resolve your conflicts that's why I have merged @Sumit11081996's PR.

If you believe your design is better, then you are always welcome to open a new issue "Improve help section".
