### ISSUE TITLE
Fix the image in submitted.html also check the responsiveness of page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#320]
![image](https://user-images.githubusercontent.com/56196640/124358820-b4d76f00-dc3f-11eb-9e07-acd0c7f48b79.png)

And replace this line "If you want to make any changes to the form before your voter id card is generated, then please click here." with "If you want to check the status of your application, then please click here."

**Comment by shreya-madhwal** [comment]
@QAZIMAAZARSHAD /assign

**Comment by devanshi-code** [comment]
@QAZIMAAZARSHAD I would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I would like to work on this issue

@devanshi-code already assigned.

**Comment by purohitmansi** [comment]
Please assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
> Please assign this to me.

Already assigned.

**Comment by shreya-madhwal** [comment]
@purohitmansi I can understand your interest but I'm already working on this issue! If I will have any problem I'll let the project admin know here.

**Comment by QAZIMAAZARSHAD** [comment]
> @purohitmansi I can understand your interest but I'm already working on this issue! If I will have any problem I'll let the project admin know here.

@shreya-madhwal it has been 8 days since you were assigned. Finish it ASAP.

**Comment by shreya-madhwal** [comment]
> > @purohitmansi I can understand your interest but I'm already working on this issue! If I will have any problem I'll let the project admin know here.
> 
> @shreya-madhwal it has been 8 days since you were assigned. Finish it ASAP.

@QAZIMAAZARSHAD okk sir!

**Comment by shreya-madhwal** [comment]
Sir @QAZIMAAZARSHAD  I've done with the task and created the PR hope now I'm done with my job. If any other changes will require then please let me know I'll sort it.
