### ISSUE TITLE
Fix the header in home and help page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#328]
![image](https://user-images.githubusercontent.com/56196640/124384884-faa04000-dcf0-11eb-9c68-e0d63b070cde.png)

**Comment by stellashank** [comment]
Working on it sir

**Comment by stellashank** [comment]
![IMG_20210705_175123](https://user-images.githubusercontent.com/79393723/124470765-a9a84e80-ddb9-11eb-85fb-7b0371443508.jpg)
Sir I fixed the Header thing.
Need to know there to place the toggle button for modes and that select language thing

**Comment by QAZIMAAZARSHAD** [comment]
Like this 
![image](https://user-images.githubusercontent.com/56196640/124471425-77e3b780-ddba-11eb-8a3d-ff26663d3acc.png)

**Comment by QAZIMAAZARSHAD** [comment]
> ![IMG_20210705_175123](https://user-images.githubusercontent.com/79393723/124470765-a9a84e80-ddb9-11eb-85fb-7b0371443508.jpg)
> Sir I fixed the Header thing.
> Need to know there to place the toggle button for modes and that select language thing

Also, zoom and select language buttons are in only home page not on the help page.

**Comment by stellashank** [comment]
![Uploading IMG_20210705_181055.jpg…]()
Done sir.
Can i now go for PR

**Comment by QAZIMAAZARSHAD** [comment]
Sure.

Also, share screenshots of both pages and a live demo link so I can review your changes.

**Comment by stellashank** [comment]
![IMG_20210705_181055](https://user-images.githubusercontent.com/79393723/124473387-e295f280-ddbc-11eb-9ce8-5ab6019e9b95.jpg)
Done sir
Can i now go for a PR

**Comment by QAZIMAAZARSHAD** [comment]
Fine

**Comment by stellashank** [comment]
![16254906757947441617362656537301](https://user-images.githubusercontent.com/79393723/124476569-9ba9fc00-ddc0-11eb-8fa9-8f477ee4a27e.jpg)
Headers of Help page as well as home page
Rectified.

**Comment by stellashank** [comment]
sir guide me through if My PR was successful or not

**Comment by QAZIMAAZARSHAD** [comment]
@stellashank u=you have not made PR yet.

**Comment by QAZIMAAZARSHAD** [comment]
After making changes you have to click on the make pull request button.

**Comment by stellashank** [comment]
Done sir. Do u confirm?!
