### ISSUE TITLE
Website Homepage black space 

### ISSUE THREAD

**Issue by PrathmeshMutke** [QAZIMAAZARSHAD/Voters-Registration-Portal#330]
## Describe the bug
In website's home page just in background of start button three images scroll horizontally one by one 
Issue :
In between images Black black space with changing alignment should be removed

## To Reproduce
1. 
2. 
3. 
4. 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).

## Environment (please complete the following information):
 - OS:
 - Browser:

**Comment by QAZIMAAZARSHAD** [comment]
@PrathmeshMutke this issue is already open https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/298.

you can try this one https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/328.
