### ISSUE TITLE
Correct the flip logo feature and also increase logo size

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#332]
![image](https://user-images.githubusercontent.com/56196640/124492656-63131e00-ddd2-11eb-9fe1-ef98e0ae203a.png)

**Comment by stellashank** [comment]
#332
Will resolve the issue in next commit sir.

**Comment by QAZIMAAZARSHAD** [comment]
@stellashank any updates.

**Comment by Garima-7** [comment]
assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
> assign me this issue.

DCP or LGMSoC?

**Comment by Garima-7** [comment]
LGMSOC

**Comment by Garima-7** [comment]
initial:-
![Screenshot (392)](https://user-images.githubusercontent.com/83363645/126031927-82fc6bfb-cd01-4129-9735-6e5020ba7185.png)
After hover:-
![image](https://user-images.githubusercontent.com/83363645/126032038-f5397b6f-cb80-406e-9b23-e53205765b61.png)

pls check if it's correct?

**Comment by Garima-7** [comment]
https://garima-7.github.io/Voters-Registration-Portal/

**Comment by Garima-7** [comment]
https://garima-7.github.io/Voters-Registration-Portal/

**Comment by Garima-7** [comment]
> https://garima-7.github.io/Voters-Registration-Portal/

pls check then will make a PR

**Comment by QAZIMAAZARSHAD** [comment]
Everything is fine except the footer of the form correction page.

Also, correct the copyright line on the form correction page.
![image](https://user-images.githubusercontent.com/56196640/126060602-007a5c0d-a7c3-4247-8049-f739a6f0c1a2.png)

**Comment by Garima-7** [comment]
> Everything is fine except the footer of the form correction page.
> 
> Also, correct the copyright line on the form correction page.
> ![image](https://user-images.githubusercontent.com/56196640/126060602-007a5c0d-a7c3-4247-8049-f739a6f0c1a2.png)

correction done
