### ISSUE TITLE
Remove `abc.css` file from several directories

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#335]
## Describe the bug
There's a redundant file named `abc.css` persist in certain folders under `.github` directory.

## To Reproduce
1.  head over to repo
2. visit inside `.github` repo

## Expected behavior
Folder structure should be proper with relevant files.

## Environment (please complete the following information):
 - OS: all
 - Browser: all

## Additional context
none

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD please confirm.

**Comment by QAZIMAAZARSHAD** [comment]
Yaa, I added them to upload files.

No use of these files.

**Comment by RiyaGupta89** [comment]
Can I work on this issue please?

**Comment by mayank-wadhwa-git** [comment]
Can I work on this issue please?

**Comment by nlok5923** [comment]
@mayank-wadhwa-git @RiyaGupta89 is already working on it so please find another issue.

**Comment by QAZIMAAZARSHAD** [comment]
@nlok5923 it has been 6 days and this is a cakewalk issue so let's give the opportunity to others.

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this issue please?

Under DCP or LGMSoC?

**Comment by mayank-wadhwa-git** [comment]
> > Can I work on this issue please?
> 
> Under DCP or LGMSoC?

DCP

**Comment by nlok5923** [comment]
> @nlok5923 it has been 6 days and this is a cakewalk issue so let's give the opportunity to others.

Agree

**Comment by RiyaGupta89** [comment]
Hey, i am sorry. I have worked on this issue earlier but i forgot to push my code. I am sorry.

**Comment by QAZIMAAZARSHAD** [comment]
> Hey, i am sorry. I have worked on this issue earlier but i forgot to push my code. I am sorry.

Your PR is not correct look into it.

**Comment by QAZIMAAZARSHAD** [comment]
The first correct PR will be accepted.
