### ISSUE TITLE
Chore fixes needed in registration form

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#336]
## Describe the bug
Currently registration form is quite uncertain in it's field UI design.

some uncertainities: 
- text area should not be resizable (try `resize: none`).
- show password fields aren't aligned properly.
- Total registration component animation on hover 

## To Reproduce
1.  Head over to registration page

## Expected behavior
registration page should not have hover animation  and fix rest two bugs 

## Logs
If applicable, add logs to help explain your problem (e.g. the error message and/or exception traceback).
![image](https://user-images.githubusercontent.com/56120084/124591997-990bdd00-de7a-11eb-9470-8248ecba4375.png)

## Environment (please complete the following information):
 - OS: all
 - Browser: all

@QAZIMAAZARSHAD please take a look i don't think the animation on hover over registration and login page looks good i think we should keep it simple and sweet.

**Comment by QAZIMAAZARSHAD** [comment]
Fine.

**Comment by QAZIMAAZARSHAD** [comment]
@nlok5923 which image is in the description?

**Comment by RiyaGupta89** [comment]
Can I work on this issue?
