### ISSUE TITLE
Fix background image of submitted page

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#338]
## Describe the bug
Currently the background image of submitted page do not covers up the whole screen

## To Reproduce
1.  Headover [here](https://qazimaazarshad.github.io/Voters-Registration-Portal/submitted.html)
2.  See error

## Expected behavior
Background image should cover the whole screen

## Logs
![image](https://user-images.githubusercontent.com/56120084/124743736-a6d56700-df3b-11eb-9eab-b2ffa6f27248.png)

## Environment (please complete the following information):
 - OS: all
 - Browser: all

## Additional context
Also remove the underline from view application status button

**Comment by QAZIMAAZARSHAD** [comment]
@nlok5923 this issue is already open.
