### ISSUE TITLE
Footer links under website policy section is not clickable.

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#339]
## Describe the bug
links under the website policy section of the footer are not clickable 

## To Reproduce
1.  head over to the website policy section inside the footer 

## Expected behavior
Footer links should be clickable
Do it for the footer of all pages.
Replace help text with something else.

## Logs
![image](https://user-images.githubusercontent.com/56120084/124744877-d3d64980-df3c-11eb-8ab5-8da77d3e5802.png)

## Environment (please complete the following information):
 - OS: all
 - Browser: all

**Comment by asdsyd** [comment]
Please assign me to work on this.

**Comment by asdsyd** [comment]
i have created a pull request please check. Thanks

**Comment by purohitmansi** [comment]
Please do assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
> Please do assign this to me.

This is already assigned.
Look for issues with Up for Grab label and issues which have remained unsolved for more than 10 days.
