### ISSUE TITLE
Add a preloader 

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Voters-Registration-Portal#34]
I want to add a attractive preloader

**Comment by kumarishalini6** [comment]
Sure

**Comment by urvashiparashar** [comment]
Can you please assign me this? @QAZIMAAZARSHAD

**Comment by souvikrajsingh** [comment]
Sir, I want to work on this, kindly assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
@urvashiparashar and @souvikrajsingh this issue has already been resolved.
