### ISSUE TITLE
Remove underline from social links inside footer.

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#340]
## Describe the bug
Currently the social links in the footer section contains underline (if seen properly) 

## To Reproduce
1.  Headover to social links section of footer

## Expected behavior
Social links button should not contain any underline.

## Logs
![image](https://user-images.githubusercontent.com/56120084/124902037-2fb5d680-e000-11eb-8e47-04bd0c0ca0d2.png)

## Environment (please complete the following information):
 - OS: all
 - Browser: all

## Additional context
none

**Comment by Cartikx3** [comment]
Assign this to me please.

**Comment by purohitmansi** [comment]
Please assign this to me.

**Comment by QAZIMAAZARSHAD** [comment]
@Cartikx3 are you working on this issue? or should I assign other participants.

**Comment by Cartikx3** [comment]
Yes sir i am working on this. Please don't assign this to others.
