### ISSUE TITLE
Add re-enter password field in forget password page.

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#344]
## Describe the bug
Currently the forget password page do not have field to confirm the new password. 

## To Reproduce
1.  headover to forget password page

## Expected behavior
There should be a confirm password field so as to make sure password is correctly entered.

## Logs
![image](https://user-images.githubusercontent.com/56120084/125152558-d74f1800-e16a-11eb-878f-53e95c13f45b.png)

## Environment (please complete the following information):
 - OS: all
 - Browser: all

## Additional context
also change login button text from "login"  -> "reset"

**Comment by Garima-7** [comment]
assign this to me please.

**Comment by nlok5923** [comment]
GFI @Garima-7 !!

**Comment by Garima-7** [comment]
Sir can you please confirm that if the person reenter the password which does not matches with initial password then I have to change the content of button from "login" -> "reset" ?

**Comment by nlok5923** [comment]
No just change the text of button. Whatever the condition is and show an alert popup if initial password don't match the password entered.

**Comment by Garima-7** [comment]
Ok Bhaiya got it.
Thanks.

**Comment by Garima-7** [comment]
Sorry for that.
 OK bhaiya I will resolve it.
