### ISSUE TITLE
Improve splash screen

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Voters-Registration-Portal#35]

**Comment by V-Yeshwanth** [comment]
I would like to work on this issue !!

**Comment by QAZIMAAZARSHAD** [comment]
@kumarishalini6 and @V-Yeshwanth I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Apply some creative effects like this https://cdn.dribbble.com/users/164756/screenshots/14613561/netflix-800x600-with-logo.gif.

**Comment by kumarishalini6** [comment]
@QAZIMAAZARSHAD can i use another netflix effect , i have tried but i am not able to make the same effect

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD can i use another netflix effect , i have tried but i am not able to make the same effect

Yaa sure, that was just an example to show you.

Use any effect.

**Comment by QAZIMAAZARSHAD** [comment]
Add this splash screen after the user logins or sign's up.

**Comment by kumarishalini6** [comment]
> Add this splash screen after the user logins or sign's up.

Ok

**Comment by nlok5923** [comment]
@QAZIMAAZARSHAD do we really need a splash screen for our website or it is a loader to load some static asset.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD do we really need a splash screen for our website or it is a loader to load some static asset.

Yes, a splash screen with the website logo will be good.

Website already has a splash screen but there are a few bugs and the style and design also need improvement that's why this issue is open.

**Comment by nlok5923** [comment]
One more doubt will user see this splash screen for a fixed time interval or the splash screen will be visible untill the content of the website loads up.

**Comment by QAZIMAAZARSHAD** [comment]
My apology,

I thought we are talking about my other project movie website.


Since this website now has already got a preloader there is no need for a splash screen.
