### ISSUE TITLE
Size Issue Of Background Image In Submitted.html

### ISSUE THREAD

**Issue by skpandey885** [QAZIMAAZARSHAD/Voters-Registration-Portal#350]
The Background Photo In The Submitted.html File Is Not Perfectly Oriented. 
And The Red Colour Overlay Is Also Not Oriented Properly. 
And Some Minor CSS Changes Required.
<br>
<img width="1440" alt="Screenshot 2021-07-11 at 12 57 24 PM" src="https://user-images.githubusercontent.com/78532081/125186341-8bbe6c00-e247-11eb-9b76-013c7a99e48e.png">

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already open. Before opening issues make sure that no other similar issue is open.

**Comment by skpandey885** [comment]
> This issue is already open. Before opening issues make sure that no other similar issue is open.

Oh Okey Bhaiya! My Bad!
