### ISSUE TITLE
Footer links appearance to be uniform

### ISSUE THREAD

**Issue by asdsyd** [QAZIMAAZARSHAD/Voters-Registration-Portal#353]
In few pages, it is appearing like a blue underline.
In few pages, a blue underline is appearing only on hover.

What needs to be done↓

Without hover, it should be a simple text(white color)
On hover text color should change to blue color, no underline.

![Screenshot_20210711-183812618 (1).jpg](https://user-images.githubusercontent.com/77977076/125196355-46199780-e277-11eb-8db8-a613b6ca18d7.jpg)

**Comment by QAZIMAAZARSHAD** [comment]
@asdsyd without hover it should be like that Feedback text.

**Comment by asdsyd** [comment]
Hey I can't work anymore on the issue as I have my university exam this week and after.  Thanks.

**Comment by mayank-wadhwa-git** [comment]
In footer, links under government of India are blue and the other links have a blue line under them.

What needs to be done?

![Feedback Form and 2 more pages - Personal - Microsoft​ Edge 11-07-2021 23_52_14](https://user-images.githubusercontent.com/68892762/125206169-5ba4b680-e2a3-11eb-9efc-2431898f0b01.png)

**Comment by RandikaR21** [comment]
Hi, I am new to open source contribution, shall I work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
> In footer, links under government of India are blue and the other links have a blue line under them.
> 
> What needs to be done?
> 
> ![Feedback Form and 2 more pages - Personal - Microsoft​ Edge 11-07-2021 23_52_14](https://user-images.githubusercontent.com/68892762/125206169-5ba4b680-e2a3-11eb-9efc-2431898f0b01.png)

You have to work on only links on the left side.
Website Policy
Terms and conditions etc.


Remove the blue underline. Without hover, it should be simple white text.
On hover text colour should change to blue like the links on the right side.

**Comment by QAZIMAAZARSHAD** [comment]
> Hi, I am new to open source contribution, shall I work on this issue?

@RandikaR21 this issue has already been assigned others were ahead of you in line.
Look for some other issues. Which have up for grab label or issues which have not been solved for more than 10 days.

**Comment by QAZIMAAZARSHAD** [comment]
@mayank-wadhwa-git you are under DCP or LGMSoC?

**Comment by mayank-wadhwa-git** [comment]
> @mayank-wadhwa-git you are under DCP or LGMSoC?

DCP

**Comment by mayank-wadhwa-git** [comment]
check it once @QAZIMAAZARSHAD 

Without Hover:
![Voter Registration Portal and 6 more pages - Personal - Microsoft​ Edge 12-07-2021 12_36_27](https://user-images.githubusercontent.com/68892762/125245312-0ce03680-e30e-11eb-877f-30819f96f99f.png)

With Hover:
![Voter Registration Portal and 6 more pages - Personal - Microsoft​ Edge 12-07-2021 12_36_39](https://user-images.githubusercontent.com/68892762/125245392-25505100-e30e-11eb-8030-14a7a6a516b0.png)

**Comment by QAZIMAAZARSHAD** [comment]
Fine.


Make sure footers in all pages are similar.

**Comment by mayank-wadhwa-git** [comment]
ok
