### ISSUE TITLE
Improve design of zoom-in/zoom-out buttons

### ISSUE THREAD

**Issue by Garima-7** [QAZIMAAZARSHAD/Voters-Registration-Portal#356]
The A+ and A- categories UI is not similar.
Will make both the UI similar so that it looks amazing and have consistent behaviour.
Assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
I don't understand the zoom-in/zoom-out buttons are similar.

Share a screenshot of what you mean.


Also since your issue concerns the zoom in/zoom out button then the title should be similar.
