### ISSUE TITLE
Header Design

### ISSUE THREAD

**Issue by jigar-sable** [QAZIMAAZARSHAD/Voters-Registration-Portal#36]
![image](https://user-images.githubusercontent.com/64949957/121292775-1ee24a00-c908-11eb-9214-63b88405ee3e.png)
### Language Options and Font Size Functionality should be in header.
I would like to create new header design.
Assign me this issue under LGM-SOC'21

**Comment by QAZIMAAZARSHAD** [comment]
> ![image](https://user-images.githubusercontent.com/64949957/121292775-1ee24a00-c908-11eb-9214-63b88405ee3e.png)
> 
> ### Language Options and Font Size Functionality should be in the header.
> I would like to create a new header design.
> Assign me this issue under LGM-SOC'21

No @jigar-sable I prefer the old design.

You can go for any other issues, open a new one, or suggest new features, etc.

**Comment by jigar-sable** [comment]
> > ![image](https://user-images.githubusercontent.com/64949957/121292775-1ee24a00-c908-11eb-9214-63b88405ee3e.png)
> > 
> > ### Language Options and Font Size Functionality should be in the header.
> > I would like to create a new header design.
> > Assign me this issue under LGM-SOC'21
> 
> No @jigar-sable I prefer the old design.
> 
> You can go for any other issues, open a new one, or suggest new features, etc.

Alright..
