### ISSUE TITLE
Font Change In The Starting Text

### ISSUE THREAD

**Issue by skpandey885** [QAZIMAAZARSHAD/Voters-Registration-Portal#361]
**This Font does Not Looks That Good!**

<img width="1440" alt="Screenshot 2021-07-12 at 10 38 44 PM" src="https://user-images.githubusercontent.com/78532081/125329263-e8627980-e362-11eb-87fa-13acca86d0ed.png">

**This Can Be done Like This:**

<img width="1440" alt="Screenshot 2021-07-12 at 10 43 57 PM" src="https://user-images.githubusercontent.com/78532081/125329509-34adb980-e363-11eb-8b23-7d3a28dcbec0.png">

**Comment by QAZIMAAZARSHAD** [comment]
Under LGMSoC?

**Comment by skpandey885** [comment]
> Under LGMSoC?

Yes bhaiya!

**Comment by nik464** [comment]
you can also assign me . I am from lgm soc.

**Comment by QAZIMAAZARSHAD** [comment]
> you can also assign me . I am from lgm soc. I will surely complete this.

Already assigned.
