### ISSUE TITLE
Validation Of Details In Feedback Form Is Not working!

### ISSUE THREAD

**Issue by skpandey885** [QAZIMAAZARSHAD/Voters-Registration-Portal#368]
If I Keep All The Fields Empty and Do not enter Any Detail Then Also The Feedback Form is getting Submitted and Do Not Show Any Warning.
It Needs To Be Fixed.
<img width="1438" alt="Screenshot 2021-07-13 at 5 52 02 PM" src="https://user-images.githubusercontent.com/78532081/125450691-fcac8df1-541e-4ee8-84bb-bd18c1a16fe6.png">

<h3>TAGS</h3>
<h1> Bug , LGMSOC<h1>

**Comment by skpandey885** [comment]
While I Was Fixing The Issue I thought Of Adding The (city, state, and zip code) Fields!
 @nlok5923  @QAZIMAAZARSHAD Bhaiya  Should I add These Fields... It Will Give a More Professional Feel To The Viewers. Shall I add It or Go with the previous One!
<img width="649" alt="Screenshot 2021-07-15 at 8 52 06 PM" src="https://user-images.githubusercontent.com/78532081/125813653-d5fcb1ea-da72-47c9-bbb3-f05b5bc1fe1a.png">

**Comment by QAZIMAAZARSHAD** [comment]
Sure go ahead.

**Comment by Junyi314** [comment]
i think i have settle the validation for this feedback form just i cannot push to it

**Comment by Junyi314** [comment]
please check
