### ISSUE TITLE
Create a login and sign-up page 

### ISSUE THREAD

**Issue by coding-geek21** [QAZIMAAZARSHAD/Voters-Registration-Portal#37]
I would like to work on this issue @QAZIMAAZARSHAD , Please assign me

**Comment by khushi-purwar** [comment]
I want to add login and signup page. I would like to work on this issue please assign me @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Go ahead @coding-geek21 and @khushi-purwar.

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by urvashiparashar** [comment]
I want to work on this issue. Can you pls assign me this? @QAZIMAAZARSHAD

**Comment by QAZIMAAZARSHAD** [comment]
Remember the first PR with better design will be accepted.

**Comment by QAZIMAAZARSHAD** [comment]
Fine @khushi-purwar.

I will review this PR soon.

**Comment by QAZIMAAZARSHAD** [comment]
Nice @coding-geek21.

I will review your PR soon.
The best design among @khushi-purwar and @coding-geek21 will be accepted.

**Comment by coding-geek21** [comment]
> Nice @coding-geek21.
> 
> I will review your PR soon.
> The best design among @khushi-purwar and @coding-geek21 will be accepted.

Thank you:)

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue @QAZIMAAZARSHAD , Please assign me

@aditya687 I have already received 2 PR's for this issue that will likely close this issue.
You are welcome to again open a new issue if you believe your design is better. Wait till I merge the above PR's.

**Comment by 1anshu-56** [comment]
I want to work on this issue can you please assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
@1anshu-56 this issue has already been resolved.

Look for some other issues.
