### ISSUE TITLE
Shift the dark light toggle button in the footer in login page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#373]

**Comment by Garima-7** [comment]
assign this to me.

**Comment by Garima-7** [comment]
![image](https://user-images.githubusercontent.com/83363645/125840305-fcdf7de2-4958-4f67-803a-a0930eaaa25e.png)
is it fine?

**Comment by Garima-7** [comment]
![image](https://user-images.githubusercontent.com/83363645/125841213-10aee9ca-0c4b-4102-a8f7-e10f585e0a56.png)
is it fine?
