### ISSUE TITLE
Correct the copyright line in form-correction.html

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#374]
![Screenshot (61)](https://user-images.githubusercontent.com/56196640/125820212-a14b114a-c9bc-43c1-bfde-2c396672c9f2.png)

**Comment by RiyaGupta89** [comment]
May i work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
> May i work on this issue?

Under DCP or LGMSoC?

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD LGMSOC.

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 this issue has already been resolved.

**Comment by QAZIMAAZARSHAD** [comment]
![image](https://user-images.githubusercontent.com/56196640/126062154-dda9ae60-d969-4a37-bac4-1d66730b57a2.png)


Correct the copyright line in form-correction.html.

**Comment by RiyaGupta89** [comment]
@QAZIMAAZARSHAD What needs to be corrected? Make the color of the copyright line darker so that it is more visible to users? This much or something else too?

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 not correct.

Make it like other pages.

![image](https://user-images.githubusercontent.com/56196640/126107600-39124ca7-259a-4e8f-bb78-d66de5432ec7.png)
