### ISSUE TITLE
Improvement of UI/UX in the voter registration home page

### ISSUE THREAD

**Issue by LeeSiangWei** [QAZIMAAZARSHAD/Voters-Registration-Portal#380]
## Is your feature request related to a problem? Please describe.
I think the UI/UX of the voter registration page can be improved

## Describe the solution you'd like
I would like to use some trending design idea of modern website design to make the interface looks clean and nice-looking

## Additional context
The adjustment of the font size is not neccessary since it does not do much changes, this can be solved by the responsive design to adjust the font size.

**Comment by QAZIMAAZARSHAD** [comment]
You can go ahead.


Show your design and ideas if It will be an improvement then I will accept it.

**Comment by QAZIMAAZARSHAD** [comment]
Under DCP or LGMSoC?

**Comment by LeeSiangWei** [comment]
nope for both

**Comment by QAZIMAAZARSHAD** [comment]
Fine.
