### ISSUE TITLE
Add mailto link in footer and correct hover effect on help button

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#382]
![image](https://user-images.githubusercontent.com/56196640/126055760-2d136bfd-cc6c-4879-a191-32a00b83ed39.png)

Add mailto link to the email. 
Remove the underline when hovering on the help desk button.
Apply the same hovering on the email button as in the hep desk button.
Also, add a similar hover effect on the toll-free button.

Make sure all the three buttons call, email, and the help desk should be of the same size.

**Comment by IwonaBaran** [comment]
Can I work on this?

**Comment by RiyaGupta89** [comment]
May I work under this issue please?

**Comment by QAZIMAAZARSHAD** [comment]
> Can I work on this?

@IwonaBaran and @RiyaGupta89 

@nagbnc have already made PR for this.
I have assigned you other issues already, resolve those first.

**Comment by aditya687** [comment]
I want to work on this issue @QAZIMAAZARSHAD . I will give a mailto in the footer and improve the hover effect on help button.

**Comment by QAZIMAAZARSHAD** [comment]
> I want to work on this issue @QAZIMAAZARSHAD . I will give a mailto in the footer and improve the hover effect on help button.

Solve other issues first.
