### ISSUE TITLE
Address of regional office should display on selecting every state

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#383]
![image](https://user-images.githubusercontent.com/56196640/126055977-3e43db74-40a9-42e2-ac38-3772b55050af.png)

![Screenshot (71)](https://user-images.githubusercontent.com/56196640/126056024-be079b42-899a-4252-8230-e69ff7b42e3a.png)

Set default address of Delhi.
No need to add all the states, only existing states in the list are fine.
The address of every state should be different.

Sample address:

NVP Regional Office, Delhi
Ground Floor, Pragati Maidan Metro Station, 
Pragati Maidan, New Delhi-110001

Update every footer.

**Comment by RiyaGupta89** [comment]
You mean to replace current address which is "Bangla sahib road ......" 
change this to "NVP Regional Office, Delhi
Ground Floor, Pragati Maidan Metro Station,
Pragati Maidan, New Delhi-110001
"

Is this what you want to be implemented?

**Comment by QAZIMAAZARSHAD** [comment]
No, don't touch that address.

You have to add a new address in the red box. 
See, like in the first screenshot.

**Comment by QAZIMAAZARSHAD** [comment]
Set default for Delhi.

But when the state changes, the address should also change.
