### ISSUE TITLE
Dark Mode / Theme is not persistent among pages.

### ISSUE THREAD

**Issue by developer-diganta** [QAZIMAAZARSHAD/Voters-Registration-Portal#397]
## Describe the bug
Dark mode / Theme is not consistent among pages. If we select dark mode on login page and go back to help page (or any other page) or even refresh the page, it loads the light theme by default.

## To Reproduce
1. Toggle Dark Mode in any page.
2. Refresh the page / go to any other page
3. Dark is not selected by default

## Expected behavior
Theme should be persistent.

**Comment by developer-diganta** [comment]
@QAZIMAAZARSHAD can I work on this?

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD can I work on this?

Under DCP or LGMSoC?

**Comment by developer-diganta** [comment]
I am actually not participating in either of the programs. Can I contribute still?

**Comment by QAZIMAAZARSHAD** [comment]
Sure.

Go ahead.

**Comment by developer-diganta** [comment]
Thank You.. Working on it!
