### ISSUE TITLE
Add test deployment link in `pull_request_template.md`

### ISSUE THREAD

**Issue by nlok5923** [QAZIMAAZARSHAD/Voters-Registration-Portal#399]
## Is your feature request related to a problem? Please describe.
It has been observed many time that contributor make changes but do not provide deployment link for testing 

## Describe the solution you'd like
Add this heading in `pull_request_template.md` inside `.github` folder 

`Deploy your changes to github page or netlify and mention deployment link:`

## Additional context
none

**Comment by anushruti11** [comment]
Can I add this under LGMSOC?
