### ISSUE TITLE
Design a new creative footer 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#4]
It will be better if you refer to some footer design of the Indian government website.

**Comment by Shivamyana19** [comment]
Can i work on this. Please assign it to me.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Naman-Joshi-14** [comment]
Sir plz can i work on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
@Naman-Joshi-14 okk,

but keep in mind since many contributors are willing to resolve this issue only the best design/solution will be accepted.

**Comment by Naman-Joshi-14** [comment]
@QAZIMAAZARSHAD  Thank you sir

**Comment by harshita9621** [comment]
Hii,  I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by Naman-Joshi-14** [comment]
@QAZIMAAZARSHAD Sir i want to add the social media logos in the image folder but I am unable to do so.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Sir i want to add the social media logos in the image folder but I am unable to do so.

don't use images try font awesome icons

**Comment by Naman-Joshi-14** [comment]
@QAZIMAAZARSHAD  ok sir

**Comment by harshita9621** [comment]
Sir can I use Icon and logo for footer design.

**Comment by QAZIMAAZARSHAD** [comment]
okk

**Comment by jatinjain001** [comment]
I would like to work on this issue
.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on this issue
> .

Already assigned

**Comment by RiyaGupta89** [comment]
May I work on this issue?

**Comment by RiyaGupta89** [comment]
![8](https://user-images.githubusercontent.com/72425181/122549490-2a441c80-d050-11eb-8049-f3b2283c18ec.png)
I resolved this issue, please review the code.

**Comment by QAZIMAAZARSHAD** [comment]
@RiyaGupta89 this issue is to completely redesign the footer.

**Comment by RiyaGupta89** [comment]
Oh okay sure. I'll do it. Do you want something else like some icon in the footer section too? Or you just want to keep this much content only and just to redesign the footer?

**Comment by QAZIMAAZARSHAD** [comment]
> Oh okay sure. I'll do it. Do you want something else like some icon in the footer section too? Or you just want to keep this much content only and just to redesign the footer?

No, you can add many things if you think it will be better.
It will be better if you refer to some footer designs of some Indian government websites.

**Comment by RiyaGupta89** [comment]
![9](https://user-images.githubusercontent.com/72425181/122638192-75256900-d110-11eb-8dba-124e0b64bd92.png)
Please have a look if it seems okay?

**Comment by RiyaGupta89** [comment]
If you want anymore changes you can let me know else can I request for the PR?
