### ISSUE TITLE
Add some spacing between form 6 and the 1st section

### ISSUE THREAD

**Issue by supzi-del** [QAZIMAAZARSHAD/Voters-Registration-Portal#40]
![image](https://user-images.githubusercontent.com/78655439/121378132-8c21c980-c960-11eb-8f52-cd3c5c90f900.png)
I can work on this if you think this is an appropriate issue.

**Comment by QAZIMAAZARSHAD** [comment]
> ![image](https://user-images.githubusercontent.com/78655439/121378132-8c21c980-c960-11eb-8f52-cd3c5c90f900.png)
> I can work on this if you think this is an appropriate issue.

No, I don't think there is any need for spacing.
You can look for any other issues or open new issues.
