### ISSUE TITLE
Shift the dark/light toggle button in footer in mobile view

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#403]

**Comment by anushruti11** [comment]
I would like to work on it under LGMSOC.

**Comment by QAZIMAAZARSHAD** [comment]
> I would like to work on it under LGMSOC.

Under DCP or LGMSoC?

**Comment by anushruti11** [comment]
> > I would like to work on it under LGMSOC.
> 
> Under DCP or LGMSoC?

LGMSoC

**Comment by anushruti11** [comment]
@nlok5923 Please take a look at the pull  request #406  and guide me what else can be implemented here for the desired output.Should I add anything else in bootstrap grid method or media queries or something else.

**Comment by nlok5923** [comment]
@anushruti11 just reopen the pr with your current changes so that we can take this discussion there also once the pr is open do provide me the test deployment link so that i can test the live changes.

**Comment by anushruti11** [comment]
> @anushruti11 just reopen the pr with your current changes so that we can take this discussion there also once the pr is open do provide me the test deployment link so that i can test the live changes.
@nlok5923 The test deployment link is in the pr description and it is closed by the project admin.

**Comment by nlok5923** [comment]
Fine you can open a new pr and there i will guide you out.

**Comment by anushruti11** [comment]
@QAZIMAAZARSHAD Is this ok?
![image](https://user-images.githubusercontent.com/65386044/126880463-4c17ba08-d568-40a5-8265-c1f68714bdd1.png)

**Comment by nlok5923** [comment]
please align the toggle button in center in mobile view also increase the size of icons.

**Comment by QAZIMAAZARSHAD** [comment]
I suggest shift the button here
![image](https://user-images.githubusercontent.com/56196640/126888447-f2e3086d-0a0f-4118-8984-1e97a981cb52.png)

**Comment by anushruti11** [comment]
> I suggest shift the button here
> ![image](https://user-images.githubusercontent.com/56196640/126888447-f2e3086d-0a0f-4118-8984-1e97a981cb52.png)

@QAZIMAAZARSHAD Only for mobile view ?

**Comment by QAZIMAAZARSHAD** [comment]
Yes only for mobile view.

**Comment by anushruti11** [comment]
> Yes only for mobile view.
@QAZIMAAZARSHAD Is this ok now?

![image](https://user-images.githubusercontent.com/65386044/126890191-60615c3f-9cd8-4d70-bed7-39af7356a5ab.png)

**Comment by QAZIMAAZARSHAD** [comment]
Yaa fine do it on every single page.
