### ISSUE TITLE
Add Captcha in Login, Sign-up and forgetPass

### ISSUE THREAD

**Issue by Kaizh3** [QAZIMAAZARSHAD/Voters-Registration-Portal#407]
## Describe the solution you'd like
Create a CAPTCHA Validation Form Using HTML, CSS, and JavaScript

## Additional context
Add any other context about the feature request here.

**Comment by QAZIMAAZARSHAD** [comment]
@Kaizh3 sign-up page already has captcha and adding it in login and forget password page will slow down the login process.
It is not necessary.

You can work on other open issues https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues?q=is%3Aopen+is%3Aissue+label%3A%22%F0%9F%A4%A9+Up+for+Grab%22.
