### ISSUE TITLE
Add Responsive Text in voter registration Help page

### ISSUE THREAD

**Issue by Kaizh3** [QAZIMAAZARSHAD/Voters-Registration-Portal#408]
## Is your feature request related to a problem? Please describe.
The text of the help page is not responsive, the mobile view of help page is weird

## Describe the solution you'd like
I would like to change the css of help page become responsive text.

![Screenshot_88](https://user-images.githubusercontent.com/86589525/126592700-984e86f4-0092-40c5-a051-0d515ce7c44c.png)

**Comment by QAZIMAAZARSHAD** [comment]
Under DCP or LGMSoC?

**Comment by Kaizh3** [comment]
Nope for both
