### ISSUE TITLE
Footer Copyright Year

### ISSUE THREAD

**Issue by Shaishav0507** [QAZIMAAZARSHAD/Voters-Registration-Portal#41]
Hey @QAZIMAAZARSHAD 
I would like to change the footer year and it will take according to the correct year.
Need not change every time.
Thanks

**Comment by QAZIMAAZARSHAD** [comment]
Nice idea,

Go ahead.

**Comment by jigar-sable** [comment]
Hii, I would like to work on this issue as LGM SOC'21 participant. Do assign me if possible. Thank You!

**Comment by QAZIMAAZARSHAD** [comment]
> Hii, I would like to work on this issue as LGM-SOC'21 participant. Do assign me if possible. Thank You!

@jigar-sable this issue is already assigned to @Shaishav0507.

Look for any other issues.

**Comment by jigar-sable** [comment]
Ok Sir

**Comment by aditya687** [comment]
Hello @QAZIMAAZARSHAD
I would like to change the footer year with the assigned or present year . Please assign me this issue for LGSOC'21

**Comment by Shaishav0507** [comment]
@QAZIMAAZARSHAD I have done it and even made a PR.
If possible check and merge it.

**Comment by QAZIMAAZARSHAD** [comment]
> Hello @QAZIMAAZARSHAD
> I would like to change the footer year with the assigned or present year . Please assign me this issue for LGSOC'21

@aditya687 this issue has already been resolved.

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD I have done it and even made a PR.
> If possible check and merge it.

I'll review your PR soon.

**Comment by MEETOZA123** [comment]
i would like to work on it

**Comment by QAZIMAAZARSHAD** [comment]
> i would like to work on it

Already assigned to others, look for any other issue.
