### ISSUE TITLE
Adjust the overlapping of dark/night toggle button in mobile view

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#428]
Shift the button slightly upwards so it does not overlap with the toll-free number button.

Do this on every page.

**Comment by aasthasaxena217** [comment]
@QAZIMAAZARSHAD Please,Assign this issue to me

**Comment by QAZIMAAZARSHAD** [comment]
> @QAZIMAAZARSHAD Please, Assign this issue to me

DCP or LGMSoC?

**Comment by aasthasaxena217** [comment]
LGMSoc
