### ISSUE TITLE
Change color of buttons in home and form-correction page

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#429]
![Screenshot (132)](https://user-images.githubusercontent.com/56196640/127266341-2a696406-19a5-4c13-899b-35e3be7dcd17.png)

**Comment by aashimawadhwa** [comment]
can you assign this issue to me ?

**Comment by QAZIMAAZARSHAD** [comment]
> can you assign this issue to me under LGMSOC'21

The pic in the description is the desired output.
