### ISSUE TITLE
Mission correcting navbar for medium and small devices

### ISSUE THREAD

**Issue by nisha331** [QAZIMAAZARSHAD/Voters-Registration-Portal#43]
The navbar looks odd when it is seen in mobile and tablet view . I as a participant at LGMSOC would like to work upon this

**Comment by sreyash8580** [comment]
I Found the Header/Navbar of the page is not responsive. It is taking total width, resulting to an ugly look. I would like to update is and make it better in terms of responsiveness.

**Comment by QAZIMAAZARSHAD** [comment]
@nisha331 and @sreyash8580 this issue is already open https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/11.
Don't open any issues which are already open, first go through every issue.
