### ISSUE TITLE
Language Selection on Registration Form

### ISSUE THREAD

**Issue by LimJinEn** [QAZIMAAZARSHAD/Voters-Registration-Portal#433]
I found out that i cant select any language when im in the registration form page. There wasnt any kind of input selection on that section of the page when i start the code on chrome using visual studio code. 
![home](https://user-images.githubusercontent.com/87891480/127764733-2e6afb40-d622-44cd-8b8e-72b6292b95e7.PNG)

**Comment by QAZIMAAZARSHAD** [comment]
![image](https://user-images.githubusercontent.com/56196640/127764827-2a6f090e-89e5-4f26-ba16-ecb1110eca5e.png)

@LimJinEn I did not find this issue on the website.


Maybe somethings wrong when we open it on the local host.

Try to fix it if you can.

**Comment by LimJinEn** [comment]
when i hover near it , the mouse icon change, showing it that it can be click, but nothing appear when i click it.
I dont know how to fix it

**Comment by QAZIMAAZARSHAD** [comment]
Fine thanks for notifying I will look into this.

If you want to work on this project you can take any Up-For-Grab issues.
