### ISSUE TITLE
enhance footer

### ISSUE THREAD

**Issue by rishika789** [QAZIMAAZARSHAD/Voters-Registration-Portal#439]
I would like to change the style of footer. The image used and colors are not going much with the website.
![q](https://user-images.githubusercontent.com/78673968/135287554-0bffa3f2-13df-491b-9f28-4be325184b2d.PNG)

**Comment by QAZIMAAZARSHAD** [comment]
You can try.
But I might reject your changes if the new style or changes is not appealing.
Also, if you change the footer of any page you have to apply the same changes on all the pages.


You can go ahead with this issue, but I suggest you should try to solve already existing issues in the footer.

**Comment by QAZIMAAZARSHAD** [comment]
If you are taking this issue.
Respond, I will assign you this issue.

Otherwise, close the issue.

**Comment by rishika789** [comment]
> You can try. But I might reject your changes if the new style or changes is not appealing. Also, if you change the footer of any page you have to apply the same changes on all the pages.
> 
> You can go ahead with this issue, but I suggest you should try to solve already existing issues in the footer.

What are the existing issues of footer?

**Comment by QAZIMAAZARSHAD** [comment]
https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/404, https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/371

**Comment by RahulRudra81** [comment]
Can I work on it??
