### ISSUE TITLE
form

### ISSUE THREAD

**Issue by rishika789** [QAZIMAAZARSHAD/Voters-Registration-Portal#440]
I would like to change the colours used in the form so that it becomes somewhat more catchy and goes with the website
![a](https://user-images.githubusercontent.com/78673968/135288402-10dfb2f0-4b42-4689-9e34-4e75d437d0a6.PNG)
.

**Comment by QAZIMAAZARSHAD** [comment]
It is not required.

I suggest you to try some other open issues.

And always give a suitable title when you open any issue.
