### ISSUE TITLE
Update Screenshots in Readme

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#442]
Add screenshots of every page.

**Comment by ManishS6** [comment]
@QAZIMAAZARSHAD I would like to work on this
Please assign this task to me.

**Comment by ManishS6** [comment]
@QAZIMAAZARSHAD I have completed the task in #444.

**Comment by ManishS6** [comment]
@QAZIMAAZARSHAD Could you please mark this as hacktober-accepted since the PR has been merged.
