### ISSUE TITLE
Add validation in Feedback form

### ISSUE THREAD

**Issue by GulshanKataria** [QAZIMAAZARSHAD/Voters-Registration-Portal#446]
## Is your feature request related to a problem? Please describe.
There is no validation in feedback form . it gets submitted directly without validating the inputs

## Describe the solution you'd like
Add validation like Email id validation,first name validation and validation to all other input fields

**Comment by GulshanKataria** [comment]
@QAZIMAAZARSHAD please assign me this issue as part of hacktoberfest

**Comment by QAZIMAAZARSHAD** [comment]
https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/368

This issue is already open.
Before opening any issue make sure no other similar issues are open.

**Comment by QAZIMAAZARSHAD** [comment]
You can work on this issue.

Go ahead.
