### ISSUE TITLE
correcting the alignment and spacing between the fields 

### ISSUE THREAD

**Issue by nisha331** [QAZIMAAZARSHAD/Voters-Registration-Portal#45]
The alignment is not that good. I as a participant of LGMSOC would like to would on it and try making it aligned.

**Comment by QAZIMAAZARSHAD** [comment]
@nisha331 can you please elaborate on the issue you intend to solve.

Share a screenshot if possible, I don't understand what you are referring to.

**Comment by prakhar07msd** [comment]
Can i work on this issue??????

**Comment by nisha331** [comment]
@QAZIMAAZARSHAD  thanks for looking into the issue . 
![Capture1](https://user-images.githubusercontent.com/76838660/121470840-62a68380-c9dc-11eb-86fe-ebc4ed4fb43d.PNG)
I was saying about shifting the the answering blocks to right and maintaining equal alignment would make it look more organized.(like the blocks in which its written* in english* *in regional* that thing)
![Capture](https://user-images.githubusercontent.com/76838660/121471910-12302580-c9de-11eb-9a87-a9406a00322e.PNG)
