### ISSUE TITLE
Updating the layout

### ISSUE THREAD

**Issue by Tejaswika** [QAZIMAAZARSHAD/Voters-Registration-Portal#55]
![image](https://user-images.githubusercontent.com/65081403/121470019-2888b200-c9db-11eb-916d-04eb7d7b8e44.png)
![image](https://user-images.githubusercontent.com/65081403/121470027-2de5fc80-c9db-11eb-8871-23cc96dfc48b.png)
A proper gap in between the Heading and Navbar is missing. Assign this issue to me, I will resolve it asap.

**Comment by QAZIMAAZARSHAD** [comment]
@Tejaswika no need for that. Also, some other issues like footer redesign are open which will fix this issue.
