### ISSUE TITLE
making the site responsive for mobile view.

### ISSUE THREAD

**Issue by jugeshraghav** [QAZIMAAZARSHAD/Voters-Registration-Portal#56]

**Comment by LizaHaddock** [comment]
Sir, I am a participant of LGMSOC-2021.
Could you please assign this issue to me.

**Comment by QAZIMAAZARSHAD** [comment]
@jugeshraghav this issue is already open https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/11.

Don't open issues before verifying that no other similar issue is open.
