### ISSUE TITLE
Make form in Kannada language

### ISSUE THREAD

**Issue by SanjeevKumar22** [QAZIMAAZARSHAD/Voters-Registration-Portal#59]
Transalate to kannada and Hindi to  full page

**Comment by QAZIMAAZARSHAD** [comment]
> Transalate to kannada and Hindi to full page

@SanjeevKumar22 this issue is already open see issue number https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/1.

If you want to make this form in the Kannada language also then go ahead.

**Comment by SanjeevKumar22** [comment]
Made transalation to all languages

**Comment by QAZIMAAZARSHAD** [comment]
> Made translation to all languages

Can you make the form in all languages?

**Comment by SanjeevKumar22** [comment]
Ya I made it

**Comment by SanjeevKumar22** [comment]
Can create PR?
