### ISSUE TITLE
Display list of supported documents

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#6]
A pop-up containing the list of supporting documents should appear on clicking "List of supported documents" link.

![image](https://user-images.githubusercontent.com/56196640/120436591-bdb4f680-c39c-11eb-97f3-925d2f09d72c.png)

Pop-up could be an image or text.

**Comment by Sourav61** [comment]
I would like to work on this issue @QAZIMAAZARSHAD

**Comment by Sourav61** [comment]
https://user-images.githubusercontent.com/70853906/120662203-90ed0600-c4a6-11eb-873a-9562787be719.mp4

**Comment by Sourav61** [comment]
Basics layout is ready just the close button is not working!! @QAZIMAAZARSHAD sir

**Comment by Sourav61** [comment]
If you have any other suggestions, pls let me know @QAZIMAAZARSHAD sir

**Comment by QAZIMAAZARSHAD** [comment]
No, You got it all wrong

In list of supported documents you have to display list like:
Adhar card for age proof
passport for address etc.

![image](https://user-images.githubusercontent.com/56196640/120663281-82531e80-c4a7-11eb-88e4-9bbbaaad8ef3.png)

And also your display design and style were not good. Try to make it attractive/improve the design.

**Comment by Sourav61** [comment]
Can i make it same way as is shown in above image @QAZIMAAZARSHAD ?

**Comment by QAZIMAAZARSHAD** [comment]
Yaa sure, 

Keep in mind you are making a list of supporting documents for the voter Id card.

**Comment by Sourav61** [comment]
okk thanks alot @QAZIMAAZARSHAD sir

**Comment by Sourav61** [comment]
https://dot.gov.in/sites/default/files/2016_11_18%20POIA-AS-II.pdf?download=1#:~:text=Card%20with%20address.-,Kisan%20Passbook%20with%20photograph%20Kisan%20Passbook%20with%20address.,older%20than%20last%20three%20months).

**Comment by Sourav61** [comment]
Can i just redirect our viewers to this document containing all information regarding list of supporting documents for the voter Id card @QAZIMAAZARSHAD ?

**Comment by QAZIMAAZARSHAD** [comment]
I wanted to have a pop-up display.

But if you are unable to do it just make this document downloadable or redirect it to that document.

I will assign this issue to someone else.

**Comment by Sourav61** [comment]
Okk i will make a pop-up display but all the supported documents should be the in same way as shown in the image or do i need to add something else @QAZIMAAZARSHAD sir?

**Comment by QAZIMAAZARSHAD** [comment]
The image you have chosen is very complex, a simple and cool design pop-up will do good.

**Comment by Sourav61** [comment]
I am talking this image sent by you 

https://user-images.githubusercontent.com/56196640/120663281-82531e80-c4a7-11eb-88e4-9bbbaaad8ef3.png

**Comment by QAZIMAAZARSHAD** [comment]
I showed you this image to explain to you what is meant by supporting documents.

**Comment by Sourav61** [comment]
okk @QAZIMAAZARSHAD sir

**Comment by Sourav61** [comment]
@QAZIMAAZARSHAD Can the modal pop-up contain an image?

**Comment by Sourav61** [comment]
Uploading 1.mp4…

**Comment by Sourav61** [comment]
Uploading 1.mp4…

**Comment by Sourav61** [comment]
@QAZIMAAZARSHAD sir pls check my work and review it!!

**Comment by QAZIMAAZARSHAD** [comment]
Nice,

**Comment by Sourav61** [comment]
Are there any others things that I should improve or include @QAZIMAAZARSHAD sir?

**Comment by QAZIMAAZARSHAD** [comment]
If you think you can improve it then you should definitely give it a try.

**Comment by Sourav61** [comment]
Okk @QAZIMAAZARSHAD sir but do we need to add some more examples of documents or these examples are enough?

**Comment by Sourav61** [comment]
Close button is working fine already, only thing that i can think of improving is adding one image or maybe changing style of text or add some more examples!!

**Comment by QAZIMAAZARSHAD** [comment]
> Okk @QAZIMAAZARSHAD sir but do we need to add some more examples of documents or these examples are enough?

It's fine, but you can if you want to.

**Comment by QAZIMAAZARSHAD** [comment]
> Close button is working fine already, the only thing that I can think of improving is adding one image or maybe changing the style of text or add some more examples!!

ok fine.

**Comment by Sourav61** [comment]
I will keep you updated sir, Thank you so much @QAZIMAAZARSHAD sir!!

**Comment by QAZIMAAZARSHAD** [comment]
Fine @Sourav61.

Wait till I review your PR.

**Comment by Sourav61** [comment]
okk @QAZIMAAZARSHAD  sir

**Comment by Sourav61** [comment]
Sir i will be able to display list of supported documents in hindi only when #207 gets resolved!!

**Comment by QAZIMAAZARSHAD** [comment]
There is no such issue.
![image](https://user-images.githubusercontent.com/56196640/122513864-a1fe5100-d028-11eb-971a-61b458459fc3.png)

Make PR its fine, and I was talking about popup in hindi.html not popup in Hindi language as well. Now their is no hindi.html.

Just add your popup in home.html and make PR.

**Comment by Sourav61** [comment]
So should the popup be submitted only in English language now @QAZIMAAZARSHAD sir?

**Comment by QAZIMAAZARSHAD** [comment]
Yes

**Comment by Sourav61** [comment]
okk @QAZIMAAZARSHAD  sir!!

**Comment by QAZIMAAZARSHAD** [comment]
Update your repo, I think you are not familiar with new changes.

**Comment by Sourav61** [comment]
I have forked and cloned just now @QAZIMAAZARSHAD sir, will make a PR very soon!!

**Comment by QAZIMAAZARSHAD** [comment]
Also, fetch upstream(Most important)

**Comment by Sourav61** [comment]
okk @QAZIMAAZARSHAD sir!!

**Comment by QAZIMAAZARSHAD** [comment]
@Sourav61 It has been 23 days and this issue is still unresolved, if you need any help you can ask @nlok5923.

**Comment by Sourav61** [comment]
@QAZIMAAZARSHAD Sir i am very sorry for delay, but i wasn't able to find any time previous few weeks as i was ill firstly due to side effects of covid vaccine and then renovation at my house i got ill for rest of time as i am allergic to dust, so i was ill for rest of the time as well. But, sir i will try my best to resolve issue as soon as possible.
Again, Sorry for the delay @QAZIMAAZARSHAD  Sir.

**Comment by QAZIMAAZARSHAD** [comment]
No problem

**Comment by Sourav61** [comment]
@QAZIMAAZARSHAD sir is this fine for modal popup width??

![Capture11](https://user-images.githubusercontent.com/70853906/123617391-d215d300-d824-11eb-95d9-6072ba35d9c9.JPG)

**Comment by QAZIMAAZARSHAD** [comment]
Ya better

**Comment by Sourav61** [comment]
But @QAZIMAAZARSHAD  sir do we need to remove scroll bar because a popup is just for information for an instance and i guess it would be fine without removing the scroll bar?

**Comment by QAZIMAAZARSHAD** [comment]
ok

**Comment by Sourav61** [comment]
Sir pls check the below video and review it!!

https://user-images.githubusercontent.com/70853906/123619903-46517600-d827-11eb-997a-bcb598abec8e.mp4

**Comment by QAZIMAAZARSHAD** [comment]
Fine make PR.
