### ISSUE TITLE
Add a page of successfully submission of the information.

### ISSUE THREAD

**Issue by tjanhvi** [QAZIMAAZARSHAD/Voters-Registration-Portal#61]

**Comment by tjanhvi** [comment]
Please assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
@tjanhvi this issue is already open https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/5.

Before opening any issue always make sure that no other similar issue is open.
