### ISSUE TITLE
Enhancing look & feel of website

### ISSUE THREAD

**Issue by 2024-SANDHYA** [QAZIMAAZARSHAD/Voters-Registration-Portal#65]
Want to change look of website as it looks a bit bland & also adding some on click functionalities using JS.

**Comment by QAZIMAAZARSHAD** [comment]
Sure go ahead if you have some ideas.

**Comment by SHUBHANSHU-creator** [comment]
can i work on this issue?

**Comment by QAZIMAAZARSHAD** [comment]
Sure go ahead

**Comment by KhushiRoy** [comment]
Can I also contribute in improvising the view of the website under LGM SOC 21,Thank You!!

**Comment by Devansh2000Shaw** [comment]
I would like to contribute on this issue under LGM SOC 21.

**Comment by Aaradhana11** [comment]
I would like to contribute on this issue .

**Comment by Aaradhana11** [comment]
I would like to contribute on this issue.

**Comment by QAZIMAAZARSHAD** [comment]
Remember only the best design will be accepted.

**Comment by tanzzz-tech** [comment]
i will like to contribute for this issue kindle assign me?

**Comment by nlok5923** [comment]
@tanzzz-tech @Aaradhana11 @Devansh2000Shaw @2024-SANDHYA @KhushiRoy @SHUBHANSHU-creator guys can you please let me know your ideas for improvising site functionalities.
