### ISSUE TITLE
Display districts of respective state in drop down list

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#7]
![image](https://user-images.githubusercontent.com/56196640/120437570-d83b9f80-c39d-11eb-9eb3-430a69bd2ad0.png)

Example - If a user selects Uttar Pradesh in state list then all the districts of Uttar Pradesh should be visible in district drop-down list.

**Comment by Barsha27** [comment]
i can work on that...

**Comment by QAZIMAAZARSHAD** [comment]
Sure, go ahead

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Barsha27** [comment]
okay...

**Comment by QAZIMAAZARSHAD** [comment]
Yes, do it.

**Comment by Barsha27** [comment]
okay..

**Comment by Barsha27** [comment]
already worked it out...

**Comment by QAZIMAAZARSHAD** [comment]
Fine @Barsha27. I'll review your PR soon.

**Comment by Barsha27** [comment]
sure
