### ISSUE TITLE
Bug:-form validation

### ISSUE THREAD

**Issue by kumarishalini6** [QAZIMAAZARSHAD/Voters-Registration-Portal#71]
I want to add validation in number input , phone number validation etc.

@QAZIMAAZARSHAD can i work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
@kumarishalini6 please don't open issues that are already open https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/issues/30.

Review all the issues first.
