### ISSUE TITLE
Adjust zoom and language buttons in mobile view

### ISSUE THREAD

**Issue by nitishapiplani** [QAZIMAAZARSHAD/Voters-Registration-Portal#77]

**Comment by nitishapiplani** [comment]
i would like to work on this if u assign to me

**Comment by QAZIMAAZARSHAD** [comment]
No need for that it will make it congested.

Fix this ->

![image](https://user-images.githubusercontent.com/56196640/121674866-39671f80-cad0-11eb-993b-19b95a8d891e.png)

Adjust this section so it looks better.

Don't change anything in desktop view, do it only for mobile view.

**Comment by nitishapiplani** [comment]
okkay

**Comment by nitishapiplani** [comment]
![git](https://user-images.githubusercontent.com/83905949/121681429-70d9ca00-cad8-11eb-85ba-0ca939f29d8a.PNG)
plzz see this once working on my mobile

**Comment by nitishapiplani** [comment]
changed some lines of code

**Comment by QAZIMAAZARSHAD** [comment]
I suggest delete the Select language text.

Also, fit the note fields marks line properly.

And apply the same header for home.html.


Do all these changes only for mobile view, don't change anything in desktop view.

**Comment by nitishapiplani** [comment]
![commit](https://user-images.githubusercontent.com/83905949/121727427-84515900-cb09-11eb-8e4c-5ccb8e90cf57.PNG)
plzz check it now

**Comment by nitishapiplani** [comment]
hey have u closed the issue 
or i can work on it
