### ISSUE TITLE
Apply creative hover effect on Tiranga image 

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#8]

**Comment by Barsha27** [comment]
i would like to work on this issue

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Barsha27** [comment]
sure

**Comment by harshita9621** [comment]
Hii,  I would like to work on this issue as LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

**Comment by QAZIMAAZARSHAD** [comment]
> Hii, I would like to work on this issue as an LGM SOC'21 participant from June 10. Do assign me if possible. Thank You!

I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.
Since many contributors are willing to resolve this issue, keep in mind the best design/solution will be accepted.

**Comment by ambivert-sam** [comment]
Hey, @QAZIMAAZARSHAD  I'm a participant of LGMSOC'21 ​I would like to contribute to this issue will you please assign it to

**Comment by QAZIMAAZARSHAD** [comment]
Since many contributors are willing to resolve this issue, keep in mind the best design/solution will be accepted.
