### ISSUE TITLE
Change the look of this button and format the text

### ISSUE THREAD

**Issue by Umesh-01** [QAZIMAAZARSHAD/Voters-Registration-Portal#81]
Since on hovering over the button, the button is being highlighted this means there is no use of that underline under the **Start** button and also this underline is effecting the look of the button. And also the line Start Your Voting Contribution is too close to the button. See this image

- [ ] Remove the underline
- [ ] Gap b/w the button and the line
- [ ] Change the color of line Start Your Voting Contribution to either green or orange

![image](https://user-images.githubusercontent.com/83420185/121711054-cffb0700-caf7-11eb-804b-bfc2bffb9e34.png)

**Comment by Umesh-01** [comment]
@QAZIMAAZARSHAD Should I work on this issue??

**Comment by QAZIMAAZARSHAD** [comment]
go ahead

**Comment by nitishapiplani** [comment]
i would like to work on it

**Comment by QAZIMAAZARSHAD** [comment]
> i would like to work on it

This issue is already assigned, look for any other issue.
