### ISSUE TITLE
Districts for a particular selected state

### ISSUE THREAD

**Issue by vaishnavi1011** [QAZIMAAZARSHAD/Voters-Registration-Portal#83]
for a selected state form drop down I want to make the dropdown for district only for the districts for that particular state.
Please assign me the issue.

**Comment by vaishnavi1011** [comment]
@QAZIMAAZARSHAD should I?

**Comment by QAZIMAAZARSHAD** [comment]
@vaishnavi1011 this issue is already open #7.

Before opening any issue always make sure that no other similar issue is open.
