### ISSUE TITLE
Add logo in title bar of website

### ISSUE THREAD

**Issue by QAZIMAAZARSHAD** [QAZIMAAZARSHAD/Voters-Registration-Portal#9]
Use the Indian flag logo or some other icon related to voting.

**Comment by QAZIMAAZARSHAD** [comment]
I'll assign you this issue when the contribution period starts from 10th June, then you can start working on this issue.

**Comment by Naman-Joshi-14** [comment]
Sir i want to work on this issue

**Comment by VaishnaviNigam25** [comment]
I would like to work on this , Please  Consider assigning me.

**Comment by SLPoojitha** [comment]
I would like to work on this issue sir. 
I have raised a pull request. Plz check if that is fine sir!!

**Comment by QAZIMAAZARSHAD** [comment]
@VaishnaviNigam25, @SLPoojitha, @Naman-Joshi-14 since this is an easy issue I cannot assign it to more than one contributor.

Look for any other issue.

**Comment by QAZIMAAZARSHAD** [comment]
This issue is already assigned to someone else.

Look for any other issues.

**Comment by QAZIMAAZARSHAD** [comment]
@shivshankar9 are you working on this.

Apply favicon on all the pages.

**Comment by shivshankar9** [comment]
Yes i am working

**Comment by QAZIMAAZARSHAD** [comment]
> Yes i am working

@shivshankar9, use this logo https://github.com/QAZIMAAZARSHAD/Voters-Registration-Portal/blob/master/Images/logo.png.
