### ISSUE TITLE
add dark mode to website

### ISSUE THREAD

**Issue by nitishapiplani** [QAZIMAAZARSHAD/Voters-Registration-Portal#97]
add toogler button for dark mode as it is currently used in every website

**Comment by pranavvdesai** [comment]
I would like to work on this

**Comment by Gauravmitra-hash** [comment]
Assign me this issue.

**Comment by QAZIMAAZARSHAD** [comment]
@nitishapiplani, @pranavvdesai and @Gauravmitra-hash this issue is already open. See issue number #28.

Before opening any issue always make sure that no other similar issue is open.
